export {
  type Vec3,
  vec3Add,
  vec3Sub,
  vec3Scale,
  vec3Dot,
  vec3Cross,
  vec3Length,
  vec3LengthSq,
  vec3HorizontalDist,
  vec3HorizontalDistSq,
  vec3Normalize,
  vec3Lerp,
  vec3RotateX,
  vec3RotateY,
  degToRad,
  radToDeg,
  VEC3_ZERO,
  VEC3_UP,
  VEC3_FORWARD,
} from "./vec3";

export {
  ballisticAngleSolver,
  gravityTargetOffset,
  ballisticTrajectoryMidpoint,
  computeSpawnOffset,
} from "./ballisticSolver";

export {
  type MoveTypeDefinition,
  type MoveTypeCategory,
  MOVE_TYPE_CATEGORIES,
  MOVE_TYPE_DEFINITIONS,
  getMoveTypeDefinition,
  getMoveTypeLabel,
  getMoveTypeCategory,
  getMoveTypesByCategory,
} from "./moveTypes";

export {
  ATTACK_TYPE_LABELS,
  getDamageForAttackType,
  getCostForAttackType,
  gutsCorrection,
  gutsTable,
  LOCK_DISTANCE_TYPES,
  getLockDistance,
} from "./damageCalculation";

export {
  type ReloadType,
  type ActionTimeline,
  type ReloadTimeline,
  type WeaponDpsInfo,
  RELOAD_TYPE_LABELS,
  RELOAD_TYPE_DESCRIPTIONS,
  CHARGE_WEAPON_TYPE_LABELS,
  SHOT_TYPE_LABELS,
  CANCEL_ROUTE_LABELS,
  GUARD_BREAK_TYPE_LABELS,
  LANDING_BEHAVIOR_LABELS,
  BULLET_TYPE_LABELS,
  getActionTimeline,
  getReloadTimeline,
  getEffectiveReloadFrames,
  simulateAmmoTimeline,
  calculateWeaponDps,
} from "./reloadSystem";

export {
  type GroundMovement,
  type AirMovement,
  type BoostSystem,
  type StepSystem,
  type GravitySystem,
  type MovementProfile,
  MOVEMENT_CLASS_LABELS,
  DASH_CANCEL_TYPE_LABELS,
  BOOST_DASH_TYPE_LABELS,
  STEP_TYPE_LABELS,
  JUMP_TYPE_LABELS,
  FALL_TYPE_LABELS,
  getGroundMovement,
  getAirMovement,
  getBoostSystem,
  getStepSystem,
  getGravitySystem,
  getMovementProfile,
  boostDashRadius,
  boostBudgetDashes,
  boostBudgetSteps,
  boostRecoveryTimeline,
  simulateBoostDashCurve,
} from "./movementPhysics";

export {
  type HitVolumeType,
  type HitVolume,
  type HitVolumeGeometry,
  HIT_TYPE_LABELS,
  COLLISION_FLAG_LABELS,
  getHitVolume,
  computeHitVolumeGeometry,
  boundingSphereRadius,
  groupHitVolumes,
  getBoneHierarchy,
} from "./collisionGeometry";

export {
  type ParamKind,
  type CrossReference,
  type CrossReferenceMap,
  BULLET_CROSS_REFERENCES,
  HITGROUP_CROSS_REFERENCES,
  INTERACTION_CROSS_REFERENCES,
  PARAM_KIND_LABELS,
  findEntryByHash,
  findEntryById,
  resolveBulletCrossReferences,
  resolveSingleReference,
  findReferencingEntries,
  buildReverseReferenceMap,
  followChildBulletChain,
} from "./crossParamResolver";

export {
  type ShootingEndReason,
  type ShootingTrajectorySummary,
  type ShootingTimeline,
  type ShootingLoopShot,
  type ShootingLoopResult,
  buildShootingTimeline,
  classifyShootingEndReason,
  simulateShootingLoop,
} from "./shootingLoop";
