import { AutoPropertyPanel } from "../shared/AutoPropertyPanel";
import type { TypedParamEntry } from "../../param-editor/typedParamTypes";
import type { TypedParamFile } from "../../param-editor/typedParamTypes";

interface CharacterPropertyPanelProps {
  entry: TypedParamEntry;
  fieldSpecs?: TypedParamFile["fieldSpecs"];
  onFieldChange: (key: string, value: number | string) => void;
}

const CHARACTER_GROUPS: Record<string, string[]> = {
  "HP & Defense": [
    "baseMaxDurability",
    "runtimeDurabilityUpperClamp",
    "hpRegenValue",
    "hpRegenValueDefault",
    "lowDurabilityIncomingDamageMultiplierBand45To50",
    "lowDurabilityIncomingDamageMultiplierBand40To45",
    "lowDurabilityIncomingDamageMultiplierBand35To40",
    "lowDurabilityIncomingDamageMultiplierBand30To35",
    "lowDurabilityIncomingDamageMultiplierBand25To30",
    "lowDurabilityIncomingDamageMultiplierBand20To25",
    "lowDurabilityIncomingDamageMultiplierBand15To20",
    "lowDurabilityIncomingDamageMultiplierBand10To15",
    "lowDurabilityIncomingDamageMultiplierBand05To10",
    "lowDurabilityIncomingDamageMultiplierBand00To05",
  ],
  "HP Ratio Dispatch A": [
    "hpRatioFamilyABand45To50",
    "hpRatioFamilyABand40To45",
    "hpRatioFamilyABand35To40",
    "hpRatioFamilyABand30To35",
    "hpRatioFamilyABand25To30",
    "hpRatioFamilyABand20To25",
    "hpRatioFamilyABand15To20",
    "hpRatioFamilyABand10To15",
    "hpRatioFamilyABand05To10",
    "hpRatioFamilyABand00To05",
  ],
  "HP Ratio Dispatch B": [
    "hpRatioFamilyBBand45To50",
    "hpRatioFamilyBBand40To45",
    "hpRatioFamilyBBand35To40",
    "hpRatioFamilyBBand30To35",
    "hpRatioFamilyBBand25To30",
    "hpRatioFamilyBBand20To25",
    "hpRatioFamilyBBand15To20",
    "hpRatioFamilyBBand10To15",
    "hpRatioFamilyBBand05To10",
    "hpRatioFamilyBBand00To05",
  ],
  "EX Burst — Incoming Damage": [
    "burstFIncomingDamageMultiplier",
    "burstSIncomingDamageMultiplier",
    "burstCIncomingDamageMultiplier",
    "burstVIncomingDamageMultiplier",
    "burstRIncomingDamageMultiplier",
  ],
  "EX Burst — Melee Attack": [
    "burstFMeleeAttackMultiplier",
    "burstSMeleeAttackMultiplier",
    "burstCMeleeAttackMultiplier",
    "burstVMeleeAttackMultiplier",
    "burstRMeleeAttackMultiplier",
  ],
  "EX Burst — Ranged Attack": [
    "burstFRangedAttackMultiplier",
    "burstSRangedAttackMultiplier",
    "burstCRangedAttackMultiplier",
    "burstVRangedAttackMultiplier",
    "burstRRangedAttackMultiplier",
  ],
  "Damage Calculation Slots": [
    "damageCalculationMultiplierSlot0",
    "damageCalculationMultiplierSlot1",
    "damageCalculationMultiplierSlot2",
    "damageCalculationMultiplierSlot3",
    "damageCalculationMultiplierSlot4",
  ],
  "EX Burst — Mobility": [
    "burstFMobilityMultiplier",
    "burstSMobilityMultiplier",
    "burstCMobilityMultiplier",
    "burstVMobilityMultiplier",
    "burstRMobilityMultiplier",
  ],
  Cost: [
    "baseUnitCost",
    "teamCostValue",
    "respawnCost",
    "mainShotCost",
    "subShotCost",
    "specialCost",
    "meleeCost",
    "burstCost",
    "assistCost",
    "subShotCostScaled",
    "chargeShotCost",
    "specialMeleeCost",
    "partnerCostPenaltyFrame",
  ],
  "Main Shot": [
    "mainShotDamage",
    "mainAmmoReloadFrame",
    "ammoCountMain",
    "ammoReserveCount",
  ],
  "Sub Shot": [
    "subShotDamage",
    "subShotCorrectionBase",
    "subAmmoReloadFrame",
  ],
  Melee: [
    "meleeDamage",
    "meleeCorrectionOffset",
    "meleeTrackingAngle",
    "meleeReachBase",
    "meleeReachDistance",
    "meleeBonusRate",
    "meleeComboLimit",
    "meleeRangeOffset",
    "meleeLockAngle",
    "meleeAimCorrectionOffset",
    "meleeLungeOffset",
    "meleeCostCorrectionOffset",
  ],
  Special: [
    "specialDamage",
    "specialReloadFrame",
    "specialMeleeDamage",
    "specialMeleeCorrectionRate",
    "specialGaugeStartRate",
  ],
  Burst: [
    "burstDamage",
    "burstCorrectionBase",
    "burstDamageMultiplier",
    "burstSpeedMultiplier",
    "burstAttributeFlags",
  ],
  Assist: ["assistDamage", "assistReloadFrame"],
  Charge: [
    "chargeTimeFrame",
    "chargeTimeOffset",
    "chargeShotDamage",
    "chargeShotCorrectionOffset",
    "chargeDamageMultiplier",
    "chargeCorrectionOffset",
    "chargeBonusOffset",
    "chargeGaugeOffset",
  ],
  "Lock-On": [
    "lockDistanceThresholdFamily1Slot0",
    "lockDistanceThresholdFamily1Slot1",
    "lockDistanceThresholdFamily1Slot2",
    "lockDistanceThresholdFamily1Slot3",
    "lockDistanceThresholdFamily1Slot4",
    "lockDistanceThresholdFamily1Default",
    "lockDistanceThresholdFamily2Slot0",
    "lockDistanceThresholdFamily2Slot1",
    "lockDistanceThresholdFamily2Slot2",
    "lockDistanceThresholdFamily2Slot4",
    "lockOnFovAngle",
    "lockOnRangeMin",
    "lockOnDistanceMax",
    "alertRangeDistance",
  ],
  "Damage Dispatch": [
    "damageDispatchValueSelector8",
  ],
  "Damage Multipliers": [
    "finalDamageMultiplier",
    "damageProrateRate",
    "comboProrateRate",
    "damageCorrectionnBase",
    "aerialDamageRate",
    "guardDamageRate",
    "barrierDamageRate",
    "mainShotDamageMultiplier",
  ],
  Movement: [
    "walkSpeed",
    "stepSpeedRate",
    "landingRecoveryRate",
    "movementType",
    "gravityMultiplier",
    "gravityOffset",
    "rotationSpeedDegrees",
  ],
  Body: [
    "modelScale",
    "bodyCollisionRadius",
    "bodyHeight",
    "bodyOffsetY",
    "hitboxHeight",
  ],
  Camera: [
    "cameraPitchDownAngle",
    "cameraDistanceNear",
    "cameraDistanceFar",
    "cameraOffsetX",
    "cameraOffsetY",
    "cameraOffsetZ",
    "cameraOffsetPartnerX",
    "cameraOffsetPartnerY",
  ],
  Radar: [
    "radarDisplayScale",
    "radarRangeDistance",
    "radarCorrectionOffset",
    "radarDisplayOffset",
    "alertRangeDistance",
    "maxRenderDistance",
    "renderCorrectionOffset",
  ],
  Aim: [
    "minimumAimAngle",
    "aimCorrectionOffsetX",
    "aimCorrectionOffsetY",
    "aimCorrectionOffsetZ",
  ],
  Attributes: [
    "unitIdComposite",
    "unitAttributeFlags",
    "weaponAttributeFlags",
    "isTransformable",
    "hasShield",
    "respawnInvincibilityFrame",
  ],
  Misc: [
    "boostGaugeMax",
    "boostRecoverySpeed",
    "downValueThreshold",
    "downValuePerHit",
    "ammoCorrectionOffset",
    "targetCorrectionOffset",
    "targetFovPct",
  ],
  Labels: ["actionLabel", "resourceLabel", "actionLabelOffset", "resourceLabelOffset"],
};

export function CharacterPropertyPanel({
  entry,
  fieldSpecs,
  onFieldChange,
}: CharacterPropertyPanelProps) {
  return (
    <AutoPropertyPanel
      entry={entry}
      fieldSpecs={fieldSpecs}
      onFieldChange={onFieldChange}
      groupOverrides={CHARACTER_GROUPS}
    />
  );
}
