import { AutoPropertyPanel } from "../shared/AutoPropertyPanel";
import type { TypedParamEntry } from "../../param-editor/typedParamTypes";
import type { TypedParamFile } from "../../param-editor/typedParamTypes";

interface CharacterPropertyPanelProps {
  entry: TypedParamEntry;
  fieldSpecs?: TypedParamFile["fieldSpecs"];
  onFieldChange: (key: string, value: number) => void;
}

const CHARACTER_GROUPS: Record<string, string[]> = {
  "HP & Defense": [
    "maxHp",
    "hpMaxValue",
    "hpCorrectionRate",
    "hpRegenValue",
    "hpRegenValueDefault",
    "hpCorrectionPctTier01",
    "hpCorrectionPctTier02",
    "hpCorrectionPctTier03",
    "hpCorrectionPctTier04",
    "hpCorrectionPctTier05",
    "hpCorrectionPctTier06",
    "hpCorrectionPctTier07",
    "hpCorrectionPctTier08",
    "hpCorrectionPctTier09",
    "hpCorrectionPctTier10",
  ],
  Cost: [
    "baseUnitCost",
    "teamCostValue",
    "respawnCost",
    "mainShotCost",
    "subShotCost",
    "specialCost",
    "meleeCost",
    "burstCost",
    "assistCost",
    "subShotCostScaled",
    "chargeShotCost",
    "specialMeleeCost",
    "partnerCostPenaltyFrame",
  ],
  "Main Shot": [
    "mainShotDamage",
    "mainShotCorrectionRate",
    "mainShotSpeedBase",
    "mainAmmoReloadFrame",
    "ammoCountMain",
    "ammoReserveCount",
  ],
  "Sub Shot": [
    "subShotDamage",
    "subShotCorrectionBase",
    "subShotCorrectionRate",
    "subDamageCorrectionnRate",
    "subAmmoReloadFrame",
  ],
  Melee: [
    "meleeDamage",
    "meleeCorrectionOffset",
    "meleeTrackingAngle",
    "meleeReachBase",
    "meleeReachDistance",
    "meleeBonusRate",
    "meleeComboLimit",
    "meleeRangeOffset",
    "meleeLockAngle",
    "meleeAimAngle",
    "meleeAimCorrectionOffset",
    "meleeLungeOffset",
    "meleeDamageCorrectionnRate",
    "meleeCostCorrectionOffset",
    "meleeCameraAngle",
  ],
  Special: [
    "specialDamage",
    "specialCorrectionBase",
    "specialCorrectionRate",
    "specialReloadFrame",
    "specialMeleeDamage",
    "specialMeleeCorrectionRate",
    "specialGaugeStartRate",
  ],
  Burst: [
    "burstDamage",
    "burstCorrectionBase",
    "burstDamageMultiplier",
    "burstSpeedMultiplier",
    "burstLockOnAngle",
    "burstAttributeFlags",
  ],
  Assist: ["assistDamage", "assistCorrectionRate", "assistReloadFrame"],
  Charge: [
    "chargeTimeFrame",
    "chargeTimeOffset",
    "chargeShotDamage",
    "chargeShotCorrectionOffset",
    "chargeDamageMultiplier",
    "chargeCorrectionOffset",
    "chargeBonusOffset",
    "chargeGaugeOffset",
  ],
  "Lock-On": [
    "redLockDistance",
    "greenLockDistance",
    "yellowLockDistance",
    "lockOnFovAngle",
    "lockOnRangeMin",
    "lockOnAngleMain",
    "lockOnDistanceMax",
    "engagementRangeNear",
    "engagementRangeFar",
    "targetSwitchDistance",
    "targetRangeDistance",
  ],
  Tracking: [
    "frontTrackingAngle",
    "rearTrackingAngle",
    "closeTrackingAngle",
    "rangedTrackingAngleMin",
    "rangedTrackingAngleMax",
    "stepTrackingAngleMin",
    "stepTrackingAngleMax",
    "projectileTrackingAngleMin",
    "projectileTrackingAngleMax",
  ],
  "Damage Multipliers": [
    "dmgMultiplierTierA",
    "dmgMultiplierTierB",
    "dmgMultiplierTierC",
    "dmgMultiplierTierD",
    "dmgMultiplierTierE",
    "dmgMultiplierTierF",
    "dmgMultiplierTierG",
    "dmgMultiplierTierH",
    "dmgMultiplierTierI",
    "finalDamageMultiplier",
    "damageProrateRate",
    "comboProrateRate",
    "damageCorrectionnBase",
    "aerialDamageRate",
    "guardDamageRate",
    "barrierDamageRate",
    "mainShotDamageMultiplier",
  ],
  Movement: [
    "walkSpeed",
    "dashSpeedBase",
    "airDashSpeedBase",
    "fallSpeedBase",
    "boostDashSpeedRate",
    "stepSpeedRate",
    "landingRecoveryRate",
    "movementSpeedBase",
    "movementType",
    "gravityMultiplier",
    "gravityOffset",
    "rotationSpeedDegrees",
  ],
  Body: [
    "modelScale",
    "bodyCollisionRadius",
    "bodyHeight",
    "bodyOffsetY",
    "hitboxHeight",
  ],
  Camera: [
    "cameraPitchDownAngle",
    "cameraPitchUpAngle",
    "cameraDistanceNear",
    "cameraDistanceFar",
    "cameraOffsetX",
    "cameraOffsetY",
    "cameraOffsetZ",
    "cameraOffsetPartnerX",
    "cameraOffsetPartnerY",
    "wideCameraAngle",
    "narrowCameraAngle",
  ],
  Radar: [
    "radarDisplayScale",
    "radarRangeDistance",
    "radarSweepAngle",
    "radarCorrectionOffset",
    "radarDisplayOffset",
    "alertRangeDistance",
    "maxRenderDistance",
    "renderCorrectionOffset",
  ],
  Aim: [
    "autoAimAngleLimit",
    "minimumAimAngle",
    "aimAssistAngle",
    "aimCorrectionOffsetX",
    "aimCorrectionOffsetY",
    "aimCorrectionOffsetZ",
  ],
  Attributes: [
    "unitIdComposite",
    "unitAttributeFlags",
    "weaponAttributeFlags",
    "isTransformable",
    "hasShield",
    "respawnInvincibilityFrame",
  ],
  Misc: [
    "boostGaugePct",
    "boostGaugeMax",
    "boostGaugeInitial",
    "boostRecoverySpeed",
    "downValueThreshold",
    "downValuePerHit",
    "shotVelocityBase",
    "ammoCorrectionOffset",
    "targetCorrectionOffset",
    "targetFovPct",
  ],
  Labels: ["actionLabelOffset", "resourceLabelOffset"],
};

export function CharacterPropertyPanel({
  entry,
  fieldSpecs,
  onFieldChange,
}: CharacterPropertyPanelProps) {
  return (
    <AutoPropertyPanel
      entry={entry}
      fieldSpecs={fieldSpecs}
      onFieldChange={onFieldChange}
      groupOverrides={CHARACTER_GROUPS}
    />
  );
}
