"""MSC research cluster catalog.

Canonical index for docs/msc-research and related MSC notes.

CodeGraph indexes this Python module (cluster ids, aliases, paths). Markdown
research notes are not in the graph; agents must match a cluster here instead
of listing docs/msc-research.

Query:
    python tools/msc_research_catalog.py --match "bird form func_143"
    python tools/msc_research_catalog.py --print wing-zero-rebellion
    python tools/msc_research_catalog.py --list
    python tools/msc_research_catalog.py --check
    python tools/msc_research_catalog.py --write-index
"""

from __future__ import annotations

from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parent.parent
MSC_RESEARCH_DIR = REPO_ROOT / "docs" / "msc-research"
INDEX_PATH = MSC_RESEARCH_DIR / "INDEX.md"
GENERATED_BANNER = (
    "<!-- Generated by tools/msc_research_catalog.py. Do not edit by hand. -->"
)


def R(*parts: str) -> str:
    return "/".join(("docs/msc-research",) + parts)


# Cluster ids as named constants so CodeGraph / rg can find them.
CLUSTER_META = "meta"
CLUSTER_TOOLCHAIN = "toolchain"
CLUSTER_SYSCALL = "syscall"
CLUSTER_RUNTIME_2C = "runtime-2c"
CLUSTER_INPUT_0C = "input-0c"
CLUSTER_MODDING = "modding"
CLUSTER_MOVEMENT = "movement"
CLUSTER_RANGED = "ranged"
CLUSTER_HOMEMADE_MOTION = "homemade-motion-clock"
CLUSTER_REGISTRY = "registry"
CLUSTER_CROSS_UNIT = "cross-unit"
CLUSTER_PARAM_MSC = "param-msc"
CLUSTER_NATIVE_UNIT_TASK = "native-unit-task"
CLUSTER_CAMERA_CLIP_BST = "camera-clip-bst"
CLUSTER_STRIKER_SYS51 = "striker-sys51"
CLUSTER_CHARGE = "charge"
CLUSTER_WING_ZERO_REBELLION = "wing-zero-rebellion"
CLUSTER_WING_ZERO_TV = "wing-zero-tv"
CLUSTER_MESSALA = "unit-messala"
CLUSTER_HAMBRABI = "unit-hambrabi"
CLUSTER_GYAN = "gyan"
CLUSTER_RX_78_2 = "unit-rx-78-2"
CLUSTER_UNICORN = "unit-unicorn"
CLUSTER_KSHATRIYA = "unit-kshatriya"
CLUSTER_SINANJU = "unit-sinanju"
CLUSTER_DELTA_PLUS = "unit-delta-plus"
CLUSTER_DELTA_KAI = "unit-delta-kai"
CLUSTER_HYAKU_SHIKI = "unit-hyaku-shiki"
CLUSTER_DIJEH = "unit-dijeh"
CLUSTER_AGE_FX = "unit-age-fx"
CLUSTER_G_SELF = "unit-g-self"
CLUSTER_MACK_KNIFE = "unit-mack-knife"
CLUSTER_NEXA_N = "unit-nexa-n"
CLUSTER_AERIAL = "unit-aerial"
CLUSTER_PHARACT = "unit-pharact"
CLUSTER_DARILBALDE = "unit-darilbalde"


@dataclass(frozen=True)
class Cluster:
    id: str
    title: str
    kind: str
    aliases: tuple[str, ...]
    read_first: tuple[str, ...]
    docs: tuple[str, ...] = ()
    related: tuple[str, ...] = ()
    settled: tuple[str, ...] = ()
    do_not: tuple[str, ...] = ()
    notes: str = ""


CLUSTERS: tuple[Cluster, ...] = (
    Cluster(
        id=CLUSTER_META,
        title="MSC research folder meta / coverage",
        kind="global",
        aliases=(
            "msc-research README",
            "gap map",
            "notion msc",
            "msc research summary",
            "docs/msc-research",
            "primer",
            "onboard an AI",
            "grok",
            "external model",
            "reading contract",
            "action shape",
            "how to read 2.c",
        ),
        read_first=(
            R("MSC_AI_PRIMER.md"),
            R("msc-evidence-grade-and-ingame-audit-protocol.md"),
            R("msc-falsified-negatives-registry.md"),
            R("INDEX.md"),
            R("README.md"),
        ),
        docs=(
            R("2026-08-27-msc-architecture-audit.md"),
            R("msc-research-gap-map.md"),
            R("notion-msc-cross-reference.md"),
            R("20260621-215819-msc-research-summary.md"),
        ),
        settled=(
            "Evidence grades are E0 guess / E1 source-pinned / E2 cross-source / E3 in-game / E3- in-game falsified.",
            "A claim is capped by the weakest link in its chain: reading X.c can never establish behaviour.",
            "Routing works (5/5 real queries hit the right cluster); the failure mode is not calling --match at all.",
            "Action-shape invariants are corpus-measured over 538 vanilla units / 1881 action bodies: callFunc3 at most once, bare-identifier argument, no callFunc/callFunc2/set_main, func_586 before the first global676 write. Zero counterexamples each.",
            "MSC_AI_PRIMER.md is self-contained and paste-able into a model with no repo access; mscdec now stamps the same contract into every decompiled X.c, and the banner is comment-only so the compiled bytecode is byte-identical.",
        ),
        do_not=(
            "Do not list docs/msc-research/ and pick notes by filename; match a cluster first.",
            "Do not publish behaviour-level policy from a source-only (E1) note.",
            "Do not propose an MSC change before grepping the falsified-negatives registry.",
            "Do not backfill Status: E3 on old notes without a real in-game run; that fabricates evidence.",
            "Do not promote a single failed build into a general prohibition without running check_msc_action_shape.py --corpus-report for counterexamples; the sys_46-in-677 ban was wrong (229 vanilla uses) and has been withdrawn.",
            "Do not delete the mscdec reading-contract banner from an X.c; it is the only guidance that travels with the file to an external model.",
        ),
        notes=(
            "Human README remains; INDEX.md is the cluster projection of this catalog. "
            "2026-08-27 audit: 65/68 notes ungraded, only 7 record in-game failures, "
            "16/31 clusters still have empty settled+do_not."
        ),
    ),
    Cluster(
        id=CLUSTER_TOOLCHAIN,
        title="MSC format, decompile, repack, AI edit blocks",
        kind="toolchain",
        aliases=(
            "mscdec",
            "msclang",
            "mscsb",
            "bscex",
            "cscex",
            "dscex",
            "pushBit",
            "AI decision",
            "opaque func ptr",
            "0x5fef",
            "func_143 offset",
            "auto rename",
            "ACTION_* naming",
            "repack crash",
            "msc_core.py",
            "msc_cfg.py",
        ),
        read_first=(
            "docs/msc-binary-format-spec.md",
            R("msc-ai-edit-block-rule.md"),
            R("msc-repack-runnable-guide.md"),
        ),
        docs=(
            R("msc-auto-rename-mapping.md"),
        ),
        related=(
            "docs/exvs2-msc-vm-native-semantics.md",
            "docs/exvs-msc-analysis.md",
            "docs/msc-system-problems-analysis.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
            "docs/agent-sessions/2026-08-03-traditional-msc-workspace.md",
            "docs/agent-sessions/msc-workspace-redesign/plan.md",
            "docs/agent-sessions/msc-human-roundtrip/process.md",
            "docs/agent-sessions/mscdec-log-regression-fix/session.md",
            "tools/check_msc_ai_blocks.py",
            "tools/check_msc_opaque_func_ptrs.py",
        ),
        settled=(
            "Game repack uses tools/msclang.py; msclang_modern.py is research-only.",
            "MSC headers are LE; script-body opcode parameters are BE.",
            "Function pointers in 0.c/2.c must be symbols (func_143), never raw offsets like 0x5fef.",
            "AI-edited X.c blocks need // AI decision and // End, origin is ... pairs.",
            "AI-block comments explain original global/func/sys traps; do not restate AI semantic names.",
        ),
        do_not=(
            "Do not invent global777/var42 names for AI-added MSC state.",
            "Do not write AI-block comments that only narrate AI semantic names.",
            "Do not use generated analysis JSON / overlays as evidence.",
        ),
    ),
    Cluster(
        id=CLUSTER_SYSCALL,
        title="Native MSC syscall notes",
        kind="global",
        aliases=(
            "sys_46",
            "sys_4F",
            "sys_4E",
            "sys_4B",
            "sys_47",
            "sys_51",
            "sys_53",
            "sys_54",
            "sys_55",
            "syscall",
            "sys_0",
        ),
        read_first=(
            "docs/exvs-msc-syscall-4f-native-handler.md",
            "docs/exvs-msc-syscall-4f-notes.md",
            R("sys46-script-parameter-atlas.md"),
        ),
        related=(
            "docs/exvs-msc-syscall-47-notes.md",
            "docs/exvs-msc-syscall-4b-notes.md",
            "docs/exvs-msc-syscall-4e-notes.md",
            "docs/exvs-msc-syscall-53-notes.md",
            R("camera-clip-bst-loader.md"),
            "docs/exvs-msc-syscall-54-notes.md",
            "docs/exvs-msc-syscall-55-notes.md",
            "docs/exvs-native-truth-mapping-workflow.md",
            "docs/exvs-native-truth-verification.md",
            R("homemade-motion-clock-vs-game-frame.md"),
        ),
        settled=(
            "Homemade NUANMB folders may not honor sys_47(0xf) / sys_47(0x7) the way stock clips do. Phase length then uses global244 -= func_274(), not func_309. See homemade-motion-clock-vs-game-frame.md.",
        ),
        do_not=(
            "Do not treat sys_47(0x5) (func_310) as a homemade clip duration or playback-speed knob. Do not wait homemade folders on sys_47(0x7).",
            "Do not treat sys_51(0x20000, 0, 0x2, slot, type) as unit-task automata. Independent 5xxxxxxxx strikers spawn only through that call. See striker-sys51.",
        ),
        notes="Syscall notes live under docs/, not docs/msc-research/.",
    ),
    Cluster(
        id=CLUSTER_CAMERA_CLIP_BST,
        title="Battle camera clip BST / vgsht2 compile loader",
        kind="global",
        aliases=(
            "camera BST",
            "clip BST",
            "CCameraMotion",
            "sub_140646AD0",
            "sub_1405DC540",
            "sub_1405DD890",
            "sub_1405AA780",
            "0x268D28",
            "qword_1421155D0",
            "0x980ABFA6",
            "sub_140647290",
            "sub_140647590",
            "sub_1405DC150",
            "0x42ACFE7D",
            "0x749B8F0E",
            "vgsht2 camera",
            "02winlose",
            "01waza",
            "00system",
            "03cpubattle",
            "camera_motion.nusktb",
            "LoadCameraClipPackage",
            "镜头 BST",
            "胜利镜头 payload",
        ),
        read_first=(
            R("camera-clip-bst-loader.md"),
            R("wing-zero-rebellion-victory-camera.md"),
            "docs/exvs-msc-syscall-53-notes.md",
        ),
        related=(
            R("wing-zero-rebellion-victory-pose.md"),
        ),
        settled=(
            "sys_53(0x4, hash) looks up 02winlose word25 clip packs, not row ids. See wing-zero-rebellion-victory-camera.md.",
            "OB camera/ has no per-clip nuanmb for those hashes. Four vgsht2 files have zero trailing bytes. Loose *.nuanmb are the menu/god CCameraMotion path.",
            "sub_1405DC540 compiles each 220-byte row into a 0x134 struct at (global+3232). sub_1405DD890 inserts those rows into the std::map at global+0x268D28, the same tree sub_140646AD0 walks. Per-hash cap 20; linear pool cap 8192.",
            "GetEntry on camera folder children 0/1/2/5 is 00system / 01waza / 02winlose / 03cpubattle. Child 3 is camera_motion; child 4 is battle/big (not clip BST).",
            "646C20 elem+32 is compiled+32 (0xC488848F). Every OB row in all four families is 0, so shipped battle clips never call sub_1406783B0. Offset 0xD20F0173 compiles to +244.",
            "Segment duration is 0x42ACFE7D at compiled +28; 647290 advances when segment_clock >= that (dur==0 means no auto-advance). Editor FOV 0x749B8F0E is 5DC150 dest +128 v0 (row+132), not v2.",
            "0x40B88DD7 and 0xC52DEBE5 have no immediates in vsac27_Release and are not copied by 5DC540. dump_compile_map.py swapped 5DC150 a5..a9 labels.",
        ),
        do_not=(
            "Do not treat battle/big.nuanmb or menu stgintro clips as winlose/waza payloads.",
            "Do not invent clip hashes, pass 02winlose row ids to sys_53, or preview from FOV+offset alone.",
            "Do not unpack FHM2D 0xCB665375; named 000common camera files already exist.",
            "Do not treat on-disk word8 0x40B88DD7 as 646C20 elem+32; that slot is compiled 0xC488848F.",
            "Do not treat word40 0xD20F0173 as duration; duration is 0x42ACFE7D.",
            "Do not trust Hex-Rays of 647590 or dump_compile_map.py block labels for 5DC150 slot order.",
        ),
        notes="Native loader research. Not an X.c edit. Insert identity pinned on OB vsac27_Release 2026-09-05.",
    ),
    Cluster(
        id=CLUSTER_RUNTIME_2C,
        title="Global 2.c runtime / action depiction architecture",
        kind="global",
        aliases=(
            "2.c",
            "func_1",
            "func_4",
            "func_44",
            "func_52",
            "func_877",
            "func_1042",
            "func_1043",
            "ACTION_*",
            "depiction",
            "2c whole file",
            "frame lifecycle",
            "action registry",
        ),
        read_first=(
            R("2c-first-hour-source-reading-roadmap.md"),
            R("msc-modder-operating-manual.md"),
        ),
        docs=(
            R("2c-source-proof-walkthrough-for-modders.md"),
            R("2c-entry-to-action-output-walkthrough.md"),
            R("2c-call-chain-runtime-flow.md"),
            R("2c-frame-lifecycle-human-trace.md"),
            R("2c-runtime-system-map-for-modding.md"),
            R("2c-whole-file-map.md"),
            R("2c-function-clusters.md"),
            R("2c-function-role-map-for-modders.md"),
            R("2c-function-responsibility-proof-handbook.md"),
            R("2c-human-readable-modding-field-guide.md"),
            R("2c-key-function-atlas-for-patching.md"),
        ),
        settled=(
            "2.c is depiction output, not the input selector.",
            "main -> func_1 -> func_877 -> func_1042/1043 -> func_4 -> func_44/52 -> ACTION_* -> syscall.",
            "Find an action from func_1043, not from func_887/888.",
        ),
        do_not=(
            "Do not treat 2.c as original C source; it is decompiled MSC.",
            "Do not start a 2.c patch at shell loadout unless the goal is shell/loadout.",
        ),
    ),
    Cluster(
        id=CLUSTER_CHARGE,
        title="CS charge-slot consumption at action entry",
        kind="global",
        aliases=(
            "CSA",
            "CSB",
            "charge slot",
            "charge consume",
            "charge reset",
            "sys_4F(0xA)",
            "ACTION_CHARGE_SHOT",
            "ACTION_MASK_1000",
            "0x800",
            "0x1000",
            "infinite charge shot",
            "0x90003",
            "ACTION_A_SHOT_BIRD_CS1",
            "bird CS",
            "SUB_SHOT_CUSTOM",
            "homemade sub-shot",
            "N副射",
            "sys_4F(0, slot, hash, 1)",
        ),
        read_first=(
            R("cs-action-charge-slot-consumption.md"),
        ),
        related=(
            "docs/exvs-msc-syscall-4f-native-handler.md",
            R("wing-zero-rebellion-bird-form-0c-input-map.md"),
        ),
        settled=(
            "A selected CS action must consume/reset its native charge slot once at action entry.",
            "Direct CSA on slot 0 uses sys_4F(0xA, 0); Rebellion CSB slot 4 is already consumed by func_1031.",
            "Do not put CSA charge clearing in an uncharged action alias or a per-tick callback.",
            "Bird CS notches consume slot 0 when sys_0(0x90003,0)==1 (TV func_1074) so the bar can refill; CS1/CS2 still consume at ENTER. That tick consume is charge-complete, not the CSA action consume. Uncharged ACTION_A_SHOT_BIRD must not consume.",
            "sys_4F(0, slot, hash, 1) zeros that slot's +0xF0/+0xF8 when +0x7C is set, same as sys_4F(0xA). CSA fire uses the bool on purpose. Uncharged fire and homemade SUB_SHOT_CUSTOM must use 3-arg sys_4F(0, slot, hash).",
        ),
        do_not=(
            "Do not assume selecting or playing a CS action automatically consumes native charge state.",
            "Do not delay charge consumption until projectile fire; an interrupted startup would preserve a reusable full charge.",
            "Do not copy CSA func_899 sys_4F(0, 0, hash, 1) onto homemade N/left/right sub-shot. The 4th arg consumes charge on that slot; a 681 of 0 dumps the CSA bar.",
            "Do not treat 3-arg slot-1 homemade sub-shot fire as enough to keep a held CSA bar. Runtime 2026-08-30: dump is the bullet frame, not press. Isolated next: do not sys_4A(0x1, 0x7) on 677; ACTION_A_SHOT CSA muzzle lives on group 7.",
        ),
    ),
    Cluster(
        id=CLUSTER_INPUT_0C,
        title="0.c input selector to 2.c action hash boundary",
        kind="global",
        aliases=(
            "0.c",
            "func_143",
            "func_95",
            "input bit",
            "action hash",
            "pending action",
            "thinker",
            "0c to 2c",
        ),
        read_first=(R("0c-to-2c-input-action-boundary.md"),),
        related=(
            "docs/exvs-msc-input-action-weapon-pipeline.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
            R("sys51-independent-striker-vs-automata.md"),
        ),
        settled=(
            "Player buttons are selected in 0.c func_143, then consumed by 2.c ACTION_*.",
            "Input-bit meaning is unit-specific; do not copy TV bits onto Rebellion.",
            "EW independent-striker sub-shot must keep sys_0(0x90000,1) and d0001 && !d000b before func_95(ACTION_AB_SUB). Skipping that gate plays the clip but native drops sys_51. Rebellion 2026-08-29 E3. See striker-sys51.",
        ),
        do_not=(
            "Do not submit 0x53554243 without the EW 0.c 0x90000/d0001 gate. Do not copy that gate onto N/left/right homemade 0x23df217e.",
        ),
    ),
    Cluster(
        id=CLUSTER_MODDING,
        title="Global MSC modding manuals and control surfaces",
        kind="global",
        aliases=(
            "modder",
            "cookbook",
            "system cards",
            "control surface",
            "patch point",
            "worked traces",
            "operating manual",
            "speed_param vs script",
        ),
        read_first=(
            R("msc-modder-operating-manual.md"),
            R("system-control-surface-matrix.md"),
            R("modding-decision-tree-system-cards.md"),
        ),
        docs=(
            R("modder-human-flow-overview.md"),
            R("modder-practical-callchain-guide.md"),
            R("modder-worked-traces.md"),
            R("modding-cookbook-action-editing.md"),
            R("modding-system-cards-handbook.md"),
            R("modding-walkthroughs-action-to-patch-points.md"),
            R("resource-control-surface-for-modders.md"),
        ),
    ),
    Cluster(
        id=CLUSTER_MOVEMENT,
        title="BD / boost / sys_46 / func_11 movement",
        kind="global",
        aliases=(
            "BD",
            "boost dash",
            "step",
            "sys_46",
            "func_11",
            "0xc000",
            "boost gate",
            "global23",
            "speedparam movement",
            "func_158",
            "recoil",
            "后坐力",
            "func_351",
            "冲到天上",
        ),
        read_first=(
            R("movement-bd-modding-workbook.md"),
            R("movement-boost-sys46-func11-map.md"),
            R("func158-shot-recoil-sys46.md"),
        ),
        docs=(
            R("sys46-script-parameter-atlas.md"),
            R("func11-c000-boost-gate-map.md"),
        ),
        settled=(
            "Ordinary BD/step is mostly speed_param + 0.c, not a 2.c ACTION_* authoring job.",
            "func_158(arg0) is shot recoil: natural backward via sys_46(0x2, 0x3, heading, pitch, arg0). Common fire value 0xfa. Operator E3 2026-08-28. No-op unless global174==1 or global180. Call once on shoot ENTER, not every tick.",
        ),
        do_not=(
            "Do not use sys_46(0x1) dash/mag writes as shot recoil. Do not call func_158 every tick. Do not treat func_158 as 足止 or analog.",
            "Do not put func_351(0x2,0x4), func_167(0x1004000), or per-tick sys_46(0x2,0x3,0,sys_0(0x40000,0x3,global39),...) on ground melee. Flight analog plus that offset as climb mag skyrockets. Keep planar func_532/global385/func_528. Registry E12.",
        ),
    ),
    Cluster(
        id=CLUSTER_RANGED,
        title="func_593 vanilla ranged quartet",
        kind="global",
        aliases=(
            "func_593",
            "func_587",
            "global676",
            "global677",
            "global678",
            "global679",
            "global680",
            "no-ammo",
            "ranged slots",
            "start shoot end",
            "callFunc",
            "callFunc2",
            "callFunc3",
            "set_main",
            "func_71",
            "func_72",
            "func_586",
            "action tick",
            "phase machine",
            "func_158",
        ),
        read_first=(R("func593-vanilla-ranged-slots.md"),),
        settled=(
            "func_593 quartet: 676 start, 677 shoot, 678 no-ammo (not cancel), 679 end.",
            "func_158(arg0) on shoot ENTER is recoil (sys_46 0x2/0x3), not a fire id. Common 0xfa. See func158-shot-recoil-sys46.md.",
            "func_587 main shot uses 677+680 fire; do not mix with the 593 quartet.",
            "The quartet is the universal EXVS2 action shape; mods must follow it. Only the four phase bodies differ per unit.",
            "Standard ENTER: func_586(); assign 676/677/678/679; exactly one callFunc3(tick); tick body is func_593().",
            "The driver advances phases via func_71(slot) = func_73 reset + global225 + func_72 dispatch. Script code only fills phase bodies and sets global252.",
            "Opcodes are E1 toolchain-pinned: callFunc 0x2f, callFunc2/set_main 0x30, callFunc3 0x31; args pushed before the function pointer, N excludes it.",
            "E2 corpus scan of 040msc/**: every 2.c uses callFunc3 (~50-120x), 0.c/1.c exactly once; set_main is rare (Rebellion 2.c has 2, both after motor-off).",
        ),
        do_not=(
            "Do not treat 678 as cancel.",
            "Do not invent a phase state machine in a callFunc3 tick to replace the 676-679 quartet.",
            "Do not callFunc3 anything but the action's own per-frame tick, and never more than once per ENTER.",
            "Do not confuse func_71 (global225 phase slot) with callFunc3 (VM opcode 0x31).",
            "callFunc/callFunc2/callFunc3 native semantics are E0 unknown. Copy the vanilla shape; do not reason from guessed behaviour.",
            "Do not copy stock func_309 / sys_47(0x7) motion-complete waits onto homemade NUANMB folders. Homemade phase length is global244 -= func_274() until that clip is E3-proven to honor the stock motion clock. See homemade-motion-clock-vs-game-frame.md.",
        ),
        related=(
            R("homemade-motion-clock-vs-game-frame.md"),
            R("func158-shot-recoil-sys46.md"),
        ),
    ),
    Cluster(
        id=CLUSTER_HOMEMADE_MOTION,
        title="Homemade NUANMB motion clock vs game-frame countdown",
        kind="global",
        aliases=(
            "func_308",
            "func_309",
            "func_310",
            "func_274",
            "func_110",
            "func_116",
            "sys_47(0x2)",
            "sys_47(0x5)",
            "sys_47(0x7)",
            "sys_47(0xf)",
            "homemade motion",
            "homemade motion clock",
            "homemade nuanmb",
            "tks11a",
            "0xa0cd8d56",
            "global244",
            "global457",
            "global276",
            "motion complete",
            "game-frame countdown",
            "自制动作时钟",
            "自制动作",
            "放慢",
        ),
        read_first=(R("homemade-motion-clock-vs-game-frame.md"),),
        related=(
            R("func593-vanilla-ranged-slots.md"),
            R("msc-falsified-negatives-registry.md"),
            R("sub-shot-custom-start-only-aim.md"),
            "docs/nuanmb-exvs2-import-in-game-layout.md",
            "docs/exvs-msc-syscall-47-notes.md",
        ),
        settled=(
            "Homemade NUANMB folders do not honor stock motion-complete the way vanilla hashes do. Phase length is global244 -= func_274() (global457, 1 frame = 0x64). Runtime 2026-08-27: Rebellion tks11a / 0xa0cd8d56 107f ≈ 1.8s.",
            "func_308 / 9-arg sys_47(0x2) only play or seek. Last func_308 arg is startTime in 0x64 units, not rate.",
            "func_73 clears global240-253 and calls func_110(0x64) on phase enter; re-arm global244 in each phase enter.",
            "Keep the func_593 quartet. This is how phase bodies wait, not a new action shape.",
        ),
        do_not=(
            "Do not wait homemade folders on func_309 / sys_47(0xf) / sys_47(0x7). E3-: ~3s wall clock; changing the frame gate does not shorten it; freeze then wait 0x7 sticks the last frame.",
            "Do not use func_310 / sys_47(0x5) / per-tick func_110 as homemade duration or playback-speed. E3-: func_310(1000) did nothing on tks11a.",
            "Do not copy stock ALT_2 0x6d149828 complete waits onto a homemade hash. Seek + global244 hold transfers; motion-complete does not.",
            "Do not diagnose packing after func_241(hash, 0) vs the real handler already proves ACTION entry.",
        ),
        notes=(
            "E3 sample is Rebellion SUB_SHOT_CUSTOM folder 0xa0cd8d56. Other homemade "
            "folders follow the same rule until E3-proven to honor the stock motion clock. "
            "Do not mix this cluster into the transform-port bootstrap."
        ),
    ),
    Cluster(
        id=CLUSTER_REGISTRY,
        title="Action/slot registry and shell loadout",
        kind="global",
        aliases=(
            "func_1044",
            "func_887",
            "func_888",
            "shell loadout",
            "slot callback",
            "global170",
            "global143",
            "sys_4B",
        ),
        read_first=(
            R("func1044-slot-callback-atlas.md"),
            R("shell-loadout-func-887-888.md"),
        ),
        docs=(R("func1044-simulated-renames.md"),),
        related=("docs/exvs-msc-func-887-888-shell-loadout-notes.md",),
        settled=(
            "func_887 selects default shell loadout; it is not the whole transform system.",
            "global143 meaning is unit-specific (WR flag on Delta Plus, form/shell on others).",
        ),
    ),
    Cluster(
        id=CLUSTER_CROSS_UNIT,
        title="Cross-unit MSC generation and Param action bridge",
        kind="global",
        aliases=(
            "cross-unit",
            "classic local selector",
            "external Param action-table",
            "legacy B4AC",
            "chrsysparam",
            "generation bridge",
        ),
        read_first=(
            R("cross-unit-msc-research-overview.md"),
            R("msc-generation-param-bridge-comparison.md"),
        ),
        docs=(R("cross-unit-first-batch-comparison.md"),),
        settled=(
            "Unit pages under docs/msc-research/units/<id>-<slug>/ are the per-unit homes.",
            "Do not use 0xBDBE6FEA as official OB v27 Delta Plus evidence.",
        ),
    ),
    Cluster(
        id=CLUSTER_PARAM_MSC,
        title="Param tables consumed by MSC / native",
        kind="global",
        aliases=(
            "speedparam",
            "characterparam",
            "armsparam",
            "bulletparam",
            "sys_0 0x60006",
            "lock-on",
            "red lock",
            "param evidence",
            "fieldBb93d195",
            "0xBB93D195",
            "weapon icon",
        ),
        read_first=(
            "docs/param-table-id-file-binding-proof.md",
            "docs/speedparam-msc-consumer-evidence.md",
            "docs/lock-on-range-native-resolution-ob.md",
        ),
        related=(
            "docs/speedparam-msc-consumer-audit.md",
            "docs/characterparam-native-consumer-map-ob.md",
            "docs/characterparam-field-notes.md",
            "docs/param-evidence-registry.tsv",
            "docs/param-editor-typed-labels-notes.md",
            R("wing-zero-rebellion-unused-form-reload-group-b.md"),
            "docs/exvs-character-weapon-icon-table.md",
        ),
        settled=(
            "sys_0 table 0x60006=speedparam, 0x60002=grapparam, 0x60007=interactionid.",
            "Red-lock is min(Family1, Family2*scale+offset-1); no single characterparam field owns it.",
        ),
        do_not=(
            "Do not treat docs/command_mapping.md or speedparam-semantic-ledger.md as current truth.",
        ),
    ),
    Cluster(
        id=CLUSTER_NATIVE_UNIT_TASK,
        title="Native unit-task automata (not MSC 0.c/2.c)",
        kind="global",
        aliases=(
            "unit-task",
            "automata",
            "automata summon",
            "throwshield",
            "hammershot",
            "vtable",
        ),
        read_first=(
            "docs/unit-task-automata-deep-analysis.md",
            "docs/unit-task-automata-process.md",
        ),
        related=(
            "docs/unit-task-automata-decompiled-analysis.md",
            "docs/unit-task-automata-ida-analysis.md",
            "docs/unit-task-automata-execute-analysis.md",
            "docs/unit-task-automata-spawn-trace.md",
            "docs/unit-task-automata-summon-analysis.md",
            "docs/unit-task-automata-vtable-reference.md",
            "docs/001gundam-throwshield-hammershot-analysis.md",
        ),
        do_not=(
            "Do not route independent 5xxxxxxxx strikers or sys_51(0x20000, 0, 0x2, slot, type) here. That is cluster striker-sys51, not automata.",
        ),
        notes="Native C++ unit-task layer for host weapons (throwshield, hammershot). Independent strikertable units are cluster striker-sys51.",
    ),
    Cluster(
        id=CLUSTER_STRIKER_SYS51,
        title="Independent striker units summoned by sys_51",
        kind="global",
        aliases=(
            "sys_51",
            "strikertable",
            "striker table",
            "516001001",
            "0xFEEB79F0",
            "independent striker",
            "CBattleStrikerManager",
            "完全独立援护",
            "独立机体召唤",
            "d0001",
            "d000b",
            "0xd0001",
            "0xd000b",
            "ACTION_AB_SUB",
            "0x53554243",
            "d0003",
            "0xd0003",
            "ACTION_MASK_UNKNOWN",
            "0x4ac375c7",
            "0x2a253f72",
            "sys_51 type",
            "action index",
        ),
        read_first=(
            R("sys51-independent-striker-vs-automata.md"),
            R("sys51-striker-action-index.md"),
            "docs/striker-research/exvs2-striker-system.md",
        ),
        related=(
            R("delta-kai-funnel-assist-slot2.md"),
            "docs/unit-task-automata-summon-analysis.md",
        ),
        settled=(
            "Independent 5xxxxxxxx strikers have their own model/MSC/param packs and are spawned only by MSC sys_51(0x20000, 0, 0x2, slot_index, type). They do not need a host bulletparam summon row.",
            "Weapon automata (CUnitTaskAutomata) are a second system: host weapons, no striker id, not strikertable.",
            "0.c must keep EW sys_0(0x90000,1) and d0001 && !d000b before submitting ACTION_AB_SUB. Skipping that gate plays the clip but native drops sys_51 spawn. Rebellion 2026-08-29 E3: restoring the gate on front/back only spawned 516001001. sys_4F consume is not required for spawn.",
            "sys_51 arg5 is the action index the spawned striker enters (sys_0(0xd0003) / ACTION_MASK_UNKNOWN_*). EW host 前后/左右/N = 0x4/0x5/0x6 for Tallgeese. 516001001 only registers index 0 -> 0x2a253f72. See sys51-striker-action-index.md.",
        ),
        do_not=(
            "Do not explain a missing 516001001 spawn by calling sys_51 the wrong class or by adding automata/bulletparam summon rows.",
            "Do not assume sys_51 slot_index 0 reads strikertable slot2.",
            "Do not submit 0x53554243 without the EW 0.c 0x90000/d0001 gate. Do not put that gate on N/left/right 0x23df217e.",
            "Do not copy EW host arg5 0x4/0x5/0x6 onto 516001001 and expect a unique attack; that id only wires index 0. Do not treat arg5 as approach-type.",
        ),
        notes="Owner-settled 2026-08-29 after a routing mix-up with native-unit-task.",
    ),
    Cluster(
        id=CLUSTER_WING_ZERO_REBELLION,
        title="Wing Zero Rebellion MSC / bird-form transform port",
        kind="unit",
        aliases=(
            "Wing Gundam Zero Rebellion",
            "wing_gundam_zero_rebellion",
            "900000004",
            "kamaesht2neo",
            "Neo Bird",
            "bird form",
            "鸟形态",
            "飞翼零式叛乱",
            "零式叛乱",
            "Rebellion",
            "FORCED_RECOVERY",
            "0x77b100ff",
            "alt2 gerobi",
            "N特射",
            "SUB_SHOT_CUSTOM",
            "SUB_SHOT_TYPE1",
            "SUB_SHOT_TYPE2",
            "SUB_SHOT_ASSIST",
            "SUB_SHOT_FLIGHT",
            "SPECIAL_SHOT_FLIGHT",
            "flight sub shot",
            "flight special gerobi",
            "0x53554243",
            "0x7e08fcc9",
            "0xd94d608f",
            "ltngfb",
            "闪电高达",
            "rebellion_hiv_lock_aim",
            "0x7cd11119",
            "0x928ca34f",
            "func_937",
            "bird melee",
            "鸟近战",
            "特格接N",
            "bird dash",
            "rebellion_enter_normal_special_n_bird_dash",
            "cut_in_loop",
            "rebellion_transform_cut_in_loop",
            "dash global143",
            "dash inertia",
            "无杆惯性",
            "rebellion_dash_untransform_keep_move",
            "tks11a",
            "0xa0cd8d56",
            "homemade motion clock",
            "0x16ed34c0",
            "0x2194f05d",
            "0x476fac14",
            "ACTION_A_SHOT_BIRD_CS1",
            "ACTION_A_SHOT_BIRD_CS2",
            "rebellion_bird_cs_stage",
            "bird CS",
            "鸟CS",
            "鸟照射",
            "slot 3",
            "slot3",
            "FLYING",
            "FLYING_EX",
            "0xfa64e4d0",
            "0x8d5b747a",
            "飛翔",
            "着地リロード",
            "reloadGroupBEnabled",
            "0xB686E88C",
            "unused form reload",
            "another mode reload",
            "自动reload",
            "另一形态",
            "group B",
            "sys_4F(0xb, 0x3, 0)",
            "sys_4F(0x16, 0x1)",
            "bird slot 1 red",
            "assist lock",
            "飞行第二槽",
            "副射红锁",
            "trans_mode_sub red",
            "前派生",
            "func_990",
            "func_991",
            "突然冲到天上",
            "flight special hit drop",
            "transform start hit drop",
            "bird special melee cancel",
            "optional landing",
            "victory pose",
            "win pose",
            "胜利pose",
            "胜利 pose",
            "winbgn",
            "winbgn01",
            "37winbgn03",
            "0xf32aa1ba",
            "func_480",
            "result pose",
            "02winlose",
            "0xfd5fd16a",
            "0x8ca6cc45",
            "victory camera",
            "winlose camera",
            "weapon icon",
            "hud icon",
            "weapon_icon",
            "fieldBb93d195",
            "0xBB93D195",
            "wep_3_h_n_b_g",
            "imcWeaponArt",
            "ms stance",
            "global170 latch",
            "飞行特格枪刀",
            "empty front back sub SE",
            "0x76b41e21",
            "前后副射音效",
            "落地不回槽",
            "rebellion_flying_reload_on_land",
            "TWINBUSTERRIFLE_EX",
            "0x54424558",
            "normal special shot EX",
            "twinbuster lightning",
            "特射闪电",
            "0x43221BFF",
            "saber beam",
            "0x2BE700A2",
            "0xdc4314cd",
            "0x5fefab7",
            "left saber",
            "光剑",
            "Zero System",
            "零式系统",
            "once per life",
            "一命一次",
            "global774",
            "0xd7fcde2",
            "0x9398ced9",
        ),
        read_first=(
            "docs/agent-sessions/2026-08-09-wing-zero-rebellion-transform-handoff.md",
            R("wing-zero-rebellion-bird-form-0c-input-map.md"),
            R("wing-zero-rebellion-flight-interrupt-form.md"),
            R("wing-zero-rebellion-slot3-flying-land-reload.md"),
            R("wing-zero-rebellion-unused-form-reload-group-b.md"),
        ),
        docs=(
            R("2026-08-09-wing-zero-rebellion-transform-port-plan.md"),
            R("2026-08-26-wing-zero-rebellion-subshot-split-and-flight-weapons-plan.md"),
            R("alt2-gerobi-stop-and-followup.md"),
            R("sub-shot-custom-start-only-aim.md"),
            R("wing-zero-rebellion-bird-melee-n-followup.md"),
            R("wing-zero-rebellion-special-n-bird-dash.md"),
            R("wing-zero-rebellion-flight-special-footstop-handbook-audit.md"),
            R("homemade-motion-clock-vs-game-frame.md"),
            R("wing-zero-rebellion-flight-hit-air-hold-and-special-melee-cancel.md"),
            R("wing-zero-rebellion-victory-pose.md"),
            R("wing-zero-rebellion-victory-camera.md"),
            R("camera-clip-bst-loader.md"),
            R("wing-zero-rebellion-flight-special-melee-ms-stance.md"),
            R("wing-zero-rebellion-empty-front-back-sub-se.md"),
            R("wing-zero-rebellion-normal-special-shot-ex.md"),
            R("wing-zero-rebellion-zero-system-once-per-life.md"),
            R("wing-zero-rebellion-bird-slot1-assist-lock.md"),
        ),
        related=(
            R("tv-wing-zero-flight-double-forward-aim.md"),
            R("tv-wing-zero-flight-special-melee-landing-copy-list.md"),
            R("tv-wing-zero-flight-special-melee-landing-todo.md"),
            R("func593-vanilla-ranged-slots.md"),
            R("sys46-script-parameter-atlas.md"),
            R("movement-boost-sys46-func11-map.md"),
            "docs/param-research/2026-08-01-speedparam-native-sys46-regrade.md",
            "work/20260809-wing-zero-rebellion-transform-plan/evidence/E-007.md",
            "work/20260809-wing-zero-rebellion-transform-plan/evidence/E-008.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
            "docs/agent-sessions/2026-08-23-wing-zero-flight-special-melee-debug.md",
            "docs/agent-sessions/2026-08-22-wing-zero-rebellion-flight-armsparam.md",
            "docs/exvs-character-weapon-icon-table.md",
            R("sys51-independent-striker-vs-automata.md"),
        ),
        settled=(
            "Bird arsenal is gated in 0.c func_143 only, not 2.c ACTION_*.",
            "Rebellion main-shot bit is 0x1 (not TV 0x100); bird form id is 0x2 (TV 0x1).",
            "Bird melee 0x2 maps to 0x928ca34f (special-melee N followup func_937); do not split 0x8b97920e; do not add that hash to the func_41 flight allowlist; do not copy Delta Plus func_888(0x8) model switch.",
            "Ground special-N dash also uses 0x928ca34f but func_241 wires rebellion_enter_normal_special_n_bird_dash; bird-form same hash still func_937. Vanilla special plays first. 2.c func_233(0x7e, 0). Special windows must func_123(0x9a1) not 0x9a5: vanilla 0x9a5 bit 0x4 native-cancels 前格 to 0xa2236f44 DIR_1 and skips the window. ACTION_B_MELEE_DIR_1 redirects to dash only when global7 is still special. Do not cancel on stick 0x3c. Do not hijack standing melee into the dash.",
            "Ground special-N dash must keep global143=0. Do not copy transform_start's global143=0x2 into cut_in_loop/676/677. Publishing form 0x2 on hash 0x928ca34f switches 0.c to the bird table, re-ENTERS func_937, and func_41 tears form: detach looks like it never ran, and 30f stick cannot pick native 0x77b100ff. 0x2 belongs only to 0x9475130e transform_start/loop.",
            "No-stick dash inertia (runtime 2026-08-27): keep writing sys_46(0x1, 0x1) with func_296(0x3e8,1) and func_167(0x1004000). Decay mag 90%/frame, pitch -20deg. Visual untransform like natural_exit (do not func_169(0x4000) on 679 start). Stick 679 only sets 252 so 0.c picks analog. Wiki BD inertia is engine BD leftover; this dash never used BD.",
            "Hit/interrupt is FORCED_RECOVERY; do not requeue 0x77b100ff.",
            "Runtime 2026-08-28: generic hit returns body/form/control to normal but wing can retain trans_loop. func_41 bypasses func_882's wing refresh; current E1 build adds func_1025(2) + sys_47(0x43,0xf6c1a9c1) after normal shell rebuild.",
            "Action hash is not form; form lives in global143.",
            "Do not tear form only on standing idle 0x6d00aeaa.",
            "678 is no-ammo, not cancel.",
            "Locate resources by canonical names, never by package hash.",
            "Flight-special custom foot-stop/restore adapters were E3- and are historical only. Literal PMX-000 Messala func_970 (func_593(); func_167(0x1004000); every tick) plus Messala 452/453/454, with Rebellion clamp/face/stop_aim removed, is E3- 2026-08-30 I7: START/SHOOT/END all stick-follow, foot-stop gone. Messala hover is not portable. See messala-flight-sub-shot-flow.md.",
            "Homemade SUB_SHOT_CUSTOM folder 0xa0cd8d56 (tks11a) phase length is global244 -= func_274(), not func_309/sys_47(0x7). func_308 seeks pose. func_310 is not a homemade rate knob. Runtime 2026-08-27: 107f ≈ 1.8s. See homemade-motion-clock-vs-game-frame.md.",
            "Bird CS is TV three hashes via field 0x100 (rebellion_bird_cs_stage), not a 0x800 alias. 0=0x476fac14 CDA9F561/562, 1=0x16ed34c0 CDA9F55A/B, 2=0x2194f05d CDA9F55C/D. 0.c 0x1 and 0x800 share the selector. Do not reuse global157 (func_44 writes global27).",
            "Rebellion HUD slot 3 is EW 飛翔 FLYING 0xFA64E4D0 (awakening FLYING_EX 0x8D5B747A): type-2 300f, land gate sys_4F(0x15,3)+global772+global24 0x1000000. Bird ENTER may sys_4F(0xb,3,0) like TV HUD. EXIT must rebind 0xFA64E4D0 and if global772==1 immediately sys_4F(0x15,3,0) (func_1034(4)). Runtime 2026-08-29 E3. See wing-zero-rebellion-slot3-flying-land-reload.md.",
            "Unused-form auto-reload after a bird swap is armsparam reloadGroupBEnabled (0xB686E88C), not MSC sys_4F(0x15). BindSlot sets the old controller to slot 9; SelectReloadDurations then uses group B, or duration 0 if the flag is off. Runtime 2026-08-31 E3: set the flag on the six paired slot 0/1/2 rows only. See wing-zero-rebellion-unused-form-reload-group-b.md.",
            "Victory pose is engine hash 0xf32aa1ba -> func_480 -> slot 0x34 -> func_74(0x4e) on tables 0x3/0x4, not a new ACTION hash. Default clip 0x8d761fe5 winbgn01; func_186()==1 clip 0x5aa9d1f6 37winbgn03. See wing-zero-rebellion-victory-pose.md.",
            "Victory camera sys_53(0x4, hash) looks up 02winlose word25 clip packs, not row ids. OB table is 000common camera/parameters/02winlose.vgsht2 (1166 packs). Current tick 0xfd5fd16a is FOV 11. See wing-zero-rebellion-victory-camera.md.",
            "HUD art is armsparam fieldBb93d195 (0xBB93D195) into the weapon_icon Folder, not MSC slot index. TV/Hambrabi keep the same sys_4F slot and swap the row. See docs/exvs-character-weapon-icon-table.md. Rebellion bird slot 1 0x04DC0DEE index 7 = wep_3_h_n_b_g (E3 2026-09-02 user).",
            "MS hand stance is global170 (0 dual guns / else saber). Latch it in transform_start. Bird->MS restore including flight special-melee B-end must apply the latch before func_884. Do not force global170=1 on special-melee EXIT. See wing-zero-rebellion-flight-special-melee-ms-stance.md.",
            "Bird special-melee cancel shares global24 0x1000000 with the FLYING land gate. After func_41 func_169, keep-air must func_167(0x4000) not 0x1004000, and func_876 must wait for !func_287(0x3ed) before sys_4F(0x15,3,1). Do not unpause in air (I4). See wing-zero-rebellion-slot3-flying-land-reload.md §7.",
            "Empty 前后副射 0x7c1d57c2 func_912 and ammo 0x53554243 func_909 must one-shot func_309(global20, 0x1f4) with global241. Unlatched sys_58 retriggers every tick. See wing-zero-rebellion-empty-front-back-sub-se.md.",
            "Normal 特射 is two independent rows like FLYING/FLYING_EX: 0x55B03548 TWINBUSTERRIFLE ammo 2 art 2, homemade 0x54424558 TWINBUSTERRIFLE_EX ammo 2 art 0xa. func_1034(3/4) swaps HUD slot 2. Bird 0x233C4626 unchanged. Do not cut ground ammo to 1. See wing-zero-rebellion-normal-special-shot-ex.md.",
            "ALT_2 first-shot lightning is only while sys_0(0xc0000): 0x43221BFF on 0xaad46c bones 0x3/0x7 group 8 through burst C/D. Non-burst first shot A/B has no that FX. Tap second shot unchanged. See alt2-gerobi-stop-and-followup.md §9.",
            "Ground special-N dash 676 must spawn 0xdc4314cd on group 6 slot 0, not group 8. Group 8 is rebellion_play_saber_beam_fx (0x2BE700A2 R slot 0 / L slot 1). 0xdc4314cd stomps the whole group; slot isolation was E3- on bird melee. stop_effects already clears group 6. See wing-zero-rebellion-special-n-bird-dash.md.",
            "Ground special-N dash INTERRUPT must call rebellion_dash_land_keep_move. global143 stays 0 so interrupt_bird_form_to_ground never runs; attach_in sys_47(0x11) sticks on guns/sabers after native func_884. Do not only zero dash_active. Do not apply the transform_start stance latch. See wing-zero-rebellion-special-n-bird-dash.md.",
            "Zero System HUD is two rows: 0xD7FCDE2 ZEROSYSTEM is the type-2 loading bar (was 1500f), 0x9398CED9 ZEROSYSTEM_START is ready CSB. Spawn binds START and global774=3. After use unbind slot 4 (do not put the loading row back). Loading-row reload times are 0; START initialAmmoCount=100. See wing-zero-rebellion-zero-system-once-per-life.md.",
        ),
        do_not=(
            "Do not treat MSC HUD slot index as the weapon_icon art index. TV/Hambrabi pick art via armsparam 0xBB93D195. Do not retarget art by binding a new slot or by sys_4F(0x16).",
            "Do not unpack FHM2D for this case; named sources already exist.",
            "Do not reopen the legacy '85 model assets missing' hash manifests.",
            "Do not mix transform-port notes with alt2 gerobi followup, SUB_SHOT_CUSTOM aim, or bird N melee 0x928ca34f.",
            "Do not copy Lightning sys_41 / 0x700000 / func_873 opaque offsets into Rebellion flight special. Do not use sys_46(0x5) as 足止: atlas names it dash/rush seed. Rebellion analog leftover is func_167(0x1004000) global24 0x4000 + sys_1(0x30001) + func_453 sys_46(0x1,mag). Foot-stop after func_593 uses func_169(0x4000), func_296(0x3e8,0), func_351(0,0x4), channel 1/2 clears and sys_46(0x4,0x4,0). Do not add the long-lived sys_46(0xF) interpolator; it previously fought EXIT analog. See wing-zero-rebellion-flight-special-footstop-handbook-audit.md.",
            "Do not rely on func_595 alone for Rebellion flight-special yaw, add the TV func_1042 START-tail yaw step, or add Bird-CS global47 |= 0x40: all three produced initial lock -> held-direction drift -> SHOOT re-lock, and the two added writers/flags had no observable effect. Remove them. func_586 resets global73 and this action never rewrites it. Before another candidate, confirm the loaded build via the existing START charge FX and 10f/40f timing markers.",
            "Do not clear flight-special direction through 2.c global87 0x3c or 0.c neutral field-0x7 republish: the combined pair produced no observable change. Remove both. The transient is not proven to be input yaw; require video or an explicit motion/effect discriminator to separate world yaw, body-local pose, motion, and camera before another edit.",
            "Do not pair the shortened flight-special 10f START with global689=0x3. Runtime showed initial lock, held-direction drift during the remaining START frames, then SHOOT re-lock; direction/shared-field masks did not help. Match Messala global689=0xa so native func_595 aim ownership spans the complete 10f START, and remove all extra input/yaw overrides.",
            "Messala global689=0xa plus the Rebellion translation/pose clamp still retained the reported entry-facing transient. Literal Messala func_970 without the clamp (2026-08-30 I7) then lost foot-stop entirely: irradiation moves with keyboard angle through START, SHOOT, and END. ACTION mix 452/453/454=0x32 then produced no observable agility change (I8): func_167 after func_593 republishes full analog leftover. Do not lower ENTER mix again. Beam slowdown must scale ch1/ch2/ch4 after func_167 while global184==2. Do not write 0 (I1/D2). Do not call this full resource equivalence because Messala motion/TRS assets remain absent.",
            "Do not restore only global24 0x4000 + the 0x30001 motor on natural flight-special EXIT. Leaving func_351 profile 0 produced air idle with bird visuals and no flight; restore profile 2 before func_598. INTERRUPT still uses FORCED_RECOVERY.",
            "Do not call rebellion_flight_special_release_flight_owner on SPECIAL_SHOT_FLIGHT 679 ENTER while rebellion_flight_special_end_hold still faces the lock: analog func_351(0x2, 0x4) restores translation and the tick still writes yaw, so the unit flies but stays locked (registry I6). Keep analog profile 0 through the 0x19 hold; restore owner on the global252 tick before func_598.",
            "Do not fix hit-stuck wing by calling func_74(0x3b): trans_end is a body+wing Folder and would override the hit body motion. Use the original wing-only func_1025(2) + sys_47(0x43,0xf6c1a9c1) refresh after func_884.",
            "Do not reintroduce rebellion_flight_special_foot_stop/lock_aim/restore_analog or private seg/frames into the current Messala port. Its load-bearing invariant is func_167(0x1004000) immediately after func_593 on every tick.",
            "Flight sub 0x7e08fcc9 untransforms at ENTER via rebellion_interrupt_bird_form_to_ground; keep it off the func_41 allowlist. Flight special 0xd94d608f keeps form; add only that hash to the allowlist. Do not use rebellion_bird_special_melee_natural_exit for flight sub.",
            "Do not mix bird N melee 0x928ca34f with TV bird special-melee landing hashes.",
            "Do not mix bird-form 0x928ca34f melee with the ground special-N dash ENTER.",
            "Do not cancel dash on analog new-press (2.c global48 0x4 is 前进). 前格 is packed 0x4 / 0xa2236f44 via special func_123(0x9a5). Drop that bit (0x9a1) and redirect DIR_1 ENTER only when global7 is special. 2.c global242 && func_233(0x7e, 0). Do not hijack standing melee into the dash.",
            "Do not write global143=0x2 from the ground special-N dash (cut_in_loop, 676 start, 677 shoot). Form stays 0; 0x2 belongs only to 0x9475130e transform_start/loop.",
            "Do not callFunc3(transform_start) or func_81(0x9475130e) from the dash; do not leave analog running in 679 without global252.",
            "Do not write the dash sys_46 inside 677; func_596 then func_300 overwrites it. Do not zero global453/global454 on ENTER (Star Winning only zeros global452). Do not follow the 0x1 write with sys_46(0x1, 0x2, ..., 0).",
            "Do not use transform_loop/ensure_mounted as the dash mount; clone loop and splice start attach_in. Do not func_81(0x77b100ff) from the dash melee hash (fake stuck flight). With global143 kept 0, 0.c ground table picks native analog after 30f stick.",
            "Do not inherit no-stick dash leftover via func_296(0)+sys_46(0x1, 0x2) (air idle/jump in-plane), sys_46(0xf) then 252 (func_44 mag 0), func_169(0x4000) on 679 start, or func_287(0x3ed) as ground after 296(0). Those yield vertical drop, fake flight pose, snap stop. Keep the 677 channel 0x1 with motor on. See wing-zero-rebellion-special-n-bird-dash.md.",
            "Do not restart from package discovery unless a bootstrap restart condition is met.",
            "Do not wait homemade SUB_SHOT_CUSTOM / tks11a / 0xa0cd8d56 on func_309 or sys_47(0x7). Do not use func_310 as homemade duration/rate. Do not diagnose packing after func_241(0x23df217e, 0) already proves ACTION entry. See homemade-motion-clock-vs-game-frame.md.",
            "Do not skip EW 0.c sys_0(0x90000,1) and d0001 && !d000b when submitting 0x53554243 ACTION_AB_SUB. Clip then plays with no 516001001. Do not put that gate on N/left/right 0x23df217e. Cluster striker-sys51, not this transform bootstrap.",
            "Do not reuse Rebellion global157 as bird CS stage; func_44 sets it to global27 on action enter. Publish sys_1(0x10000,0,0x100). Do not keep 0x2194f05d as ACTION_CHARGE_SHOT_BIRD alias of uncharged bird main.",
            "Do not unbind Rebellion slot 3 and restore FLYING without re-pause: BindSlot forces byte 318=1 and empty 飛翔 starts 5s in air. After sys_4F(0xb,3,0xfa64e4d0), if global772==1 write sys_4F(0x15,3,0). Registry I4.",
            "Do not set reloadGroupBEnabled on FLYING / FLYING_EX / Zero System. Bird unbinds slot 3; group B would tick 飛翔 in the air (I4 class). Unused-form reload is the six paired slot 0/1/2 rows only. Mode-4 adapters do not replace that flag. See wing-zero-rebellion-unused-form-reload-group-b.md.",
            "Do not sys_4F(0x16, 3, 0/1) on FLYING to hide HUD. Vanilla EW never writes slot-3 0x16; 0x16=1 shows as red disable. Gyan 0x16 is optional assist, not 飛翔. Hide with 0xB unbind. Registry I5.",
            "Do not leave func_1037 sys_4F(0x16,1,1) sticky on bird HUD slot 1. BindSlot parks ASSIST to slot 9 but does not clear byte 322. After sys_4F(0xb,1,0x04DC0DEE) and global143==0x2, one-shot sys_4F(0x16,1,0). Do not skip func_1037 on EXIT. Do not per-tick 0x16=0 in the same pack. See wing-zero-rebellion-bird-slot1-assist-lock.md.",
            "Do not write func_351(0x2,0x4), func_167(0x1004000), or per-tick sys_46(0x2) climb from sys_0(0x40000,0x3,global39) on standing BD 前派生 (func_990/func_991). Runtime 2026-08-29: 突然冲到天上. Keep ground func_351(0) and planar chase. Registry E12.",
            "Do not set global184=1 from BD 前派生 loop slashes to reopen func_516. Runtime 2026-08-29: 1 never connects to 2, infinite 1. func_492 then func_71(global629=func_990) and func_530 clears mash. Stay in func_493; chase with func_517. Registry E13.",
            "Do not put per-tick sys_46(0) lock yaw plus channel-1 mag 0x320 on DIR_2 final slash func_974. Runtime 2026-08-30: magnet tracking. Registry E18. Do not ENTER-sys_46 mag from frame 0 (E19). Start ch1 mag 0x190 at 0xc8 (E21), clear at 0xbb8 (E23). One-shot face at func_148 (E22). Ch1 pitch 0xffffdcd8 climbs (E25); 0x7d0 (+20) still high; in-game winner is 1000 (+10deg). Do not sys_46(0x2) or func_351(0x2) (E12).",
            "Do not release_flight_owner then func_296(0) on hit during 0xd94d608f / transform start/end. Keep air hold like bird melee from_flight. Do not treat analog 0x77b100ff as a keep-air global7: bird special-melee ENTER must still drop. See wing-zero-rebellion-flight-hit-air-hold-and-special-melee-cancel.md.",
            "Do not keep-form skip func_41/func_882 for bird special melee 0xc0b814ff/0x8d96c52f/0x279f0da4 while still playing ordinary Folder 0x1192E91E (F9): user still reported the dive lost. Copy-list: normal-form motion does not start on a bird owner. Dive baseline: ENTER interrupt, A to 0x708, wait until !func_287(0x3ed), then B. Cancel is wait/ground func_123(0x3bf)+func_123(0xc00000) only; do not open that window on A (F7), do not func_233/func_81, do not func_123(0x9a5) (F4), do not func_309(global20,0x960) (F8). Do not func_81(0x928ca34f).",
            "Do not add a victory pose by inventing a new action hash or fake slot 0x26. Keep 0xf32aa1ba -> func_480 -> slot 0x34; extra clips are extra func_186() branches on table 0x3/0x4 slot 0x4e. Do not retarget func_241(0xf32aa1ba, func_871). Do not edit func_835 group 0x7 for the win clip. See wing-zero-rebellion-victory-pose.md.",
            "Do not pick victory cameras by mining 2.c sys_53, inventing hashes, passing 02winlose row ids, or using 01waza/00system clips. Swap func_870 word25 only from OB 02winlose packs. See wing-zero-rebellion-victory-camera.md.",
            "Do not unlock victory-pose GBL_RT with func_97(0) / sys_47(0x4, global20, 0). Runtime 2026-09-05 still glued to ground (registry H4). Author CENTER_RT / BASE in the homemade clip. Do not retry analog-2 climb (E12). See wing-zero-rebellion-victory-pose.md.",
            "Do not force global170=1 on rebellion_bird_special_melee_natural_exit or landing B-end. That always returns saber after a gun ENTER. Do not force dual guns on restore (broke saber->bird->saber). Latch at transform_start; do not apply the latch on dash restore. See wing-zero-rebellion-flight-special-melee-ms-stance.md.",
            "Do not keep-air bird special-melee cancel with func_167(0x1004000) after func_169(0x1010000). That rewrites the FLYING land-gate bit; sidestep land then never starts slot-3 5s. Use func_167(0x4000) and open reload on !func_287(0x3ed). Do not sys_4F(0x16). Do not unpause in air. See wing-zero-rebellion-slot3-flying-land-reload.md §7.",
            "Do not leave func_912 / func_909 sys_58 under bare func_309(global20, 0x1f4). Reached-time retriggers the fire SE every tick. Latch global241. See wing-zero-rebellion-empty-front-back-sub-se.md.",
            "Do not give normal 特射 awakening ammo by editing MSC consume or by sys_4F(0x16). Copy the FLYING BindSlot pair: a second armsparam row plus func_1034(3/4). Do not cut ground TWINBUSTERRIFLE from 2 ammo to 1; only the EX row changes art to 0xa. Do not append the new entryId after FLYING. Do not set reloadGroupBEnabled on FLYING. See wing-zero-rebellion-normal-special-shot-ex.md.",
            "Do not put ALT_2 first-shot 0x43221BFF on non-burst A/B. Only sys_0(0xc0000) first shot C/D keeps the tap-second-shot helper. Do not sys_4A(0xb, 0x8) on the burst C/D fire tick: that wipes group 8. See alt2-gerobi-stop-and-followup.md §9.",
            "Do not spawn dash 676 0xdc4314cd on sys_4A group 8. That group is saber 0x2BE700A2. Use group 6 like stop_effects and bird melee isolation. Changing only the slot on group 8 is not enough. See wing-zero-rebellion-special-n-bird-dash.md.",
            "Do not leave dash INTERRUPT as flag-only in func_41. global143 stays 0 so interrupt_bird_form_to_ground never runs; attach_in sys_47(0x11) sticks on guns/sabers after func_884 remount. Call rebellion_dash_land_keep_move. Do not restore_ms_after_bird on dash. See wing-zero-rebellion-special-n-bird-dash.md.",
            "Do not bind Zero System loading row 0xD7FCDE2 after use or at spawn — that entry is the reload HUD on slot 4. Spawn 0x9398CED9; spent sys_4F(0xb,4,0). Do not func_1034(0) on bird in/out, func_1034(1) mid-life, group B, or sys_4F(0x16) on slot 4. See wing-zero-rebellion-zero-system-once-per-life.md.",
        ),
        notes="AGENTS.md still inlines this bootstrap. Sibling Rebellion MSC edits: alt2-gerobi, sub-shot-custom, bird-melee-n-followup, special-n-bird-dash, 2026-08-26 subshot-split-and-flight-weapons plan.",
    ),
    Cluster(
        id=CLUSTER_WING_ZERO_TV,
        title="TV Wing Zero source behavior for the Rebellion port",
        kind="unit",
        aliases=(
            "TV Wing Zero",
            "28001001",
            "028gunwtv_001gunwtv_001",
            "028gunwtv",
            "TV Zero",
            "special melee landing",
            "double forward aim",
        ),
        read_first=(
            R("tv-wing-zero-flight-double-forward-aim.md"),
            R("tv-wing-zero-flight-special-melee-landing-copy-list.md"),
        ),
        docs=(R("tv-wing-zero-flight-special-melee-landing-todo.md"),),
        related=(
            "docs/agent-sessions/2026-08-09-wing-zero-rebellion-transform-handoff.md",
        ),
        do_not=(
            "Do not copy TV input bits or TV interrupt requeue onto Rebellion as-is.",
            "Do not treat TV func_1078 sys_4F(0xb, 0x3, 0) as a generic 'hide HUD slot 3 in bird form' rule. TV slot 3 is ROLLING_BUSTER 0xF44BB746; Rebellion slot 3 is EW 飛翔. See wing-zero-rebellion-slot3-flying-land-reload.md.",
        ),
    ),
    Cluster(
        id=CLUSTER_MESSALA,
        title="Messala flight-mode sub-shot MSC flow",
        kind="unit",
        aliases=(
            "Messala",
            "メッサーラ",
            "002zgundm_003mesala_001",
            "flight sub shot",
            "0x9a74bce6",
            "ACTION_AB_SUB_LOCK_SWITCH",
            "func_970",
        ),
        read_first=(R("messala-flight-sub-shot-flow.md"),),
        related=(R("func593-vanilla-ranged-slots.md"),),
        settled=(
            "Messala flight gate is global20 & 0x4000; flight sub input 0x80 selects 0x9a74bce6 ACTION_AB_SUB_LOCK_SWITCH.",
            "The complete tick is func_593(); func_167(0x1004000); on every phase, so flight ownership is continuous through 679/598 rather than reconstructed on EXIT.",
            "Messala and Rebellion func_167/308/351/586/593-598 are text-identical, so the quartet/tick shape is directly portable.",
            "Messala func_893/894/895/896 are model-part sys_47 TRS only, not movement or handoff owners.",
            "Rebellion runtime 2026-08-28: continuous owner gives correct lock, firing, and natural EXIT, but target translation remains. Target adapter clears ch1/ch2, case-4 vector and func_300(0) after func_167; it preserves 0x4000/motor/global714 and skips global184==4.",
            "Rebellion runtime follow-up: translation clamp stops position and preserves EXIT; left/right input still changes body-local bank. Pose adapter zeros func_104/107 during ACTIVE only, preserving sys_46 world yaw and skipping 679.",
            "Rebellion loop-motion runtime: a synthetic 10f 679 wait leaves player control active while action lock/pose still owns the unit. Target 679 must cleanup then set global252 immediately; Messala motion-end wait requires a real recovery clip.",
        ),
        do_not=(
            "Do not copy Messala motion/projectile hashes, form id 1, speed row c2b19d12, or opaque func_893-896 into Rebellion.",
            "Do not copy only Messala ENTER calls; the load-bearing behavior is func_167(0x1004000) after func_593 on every tick including EXIT.",
            "Do not use Messala's motion-end 679 predicate with Rebellion's intentionally looping 0x9de587ce motion; keep a bounded target recovery timer.",
            "Do not claim full visual/resource Messala equivalence from a green lifecycle contract; motion c8fd1afb and private TRS/weapon resources are absent. For the confirmed movement-only delta, do not destroy continuous flight ownership: clamp translation after func_167 and skip 679.",
        ),
    ),
    Cluster(
        id=CLUSTER_HAMBRABI,
        title="Hambrabi flight-mode sub-shot 側転射撃 and the param-table generation",
        kind="unit",
        aliases=(
            "Hambrabi",
            "ハンブラビ",
            "002zgundm_006hambrb_001",
            "変形サブ射撃",
            "側転射撃",
            "前進射撃",
            "背部ビームライフル",
            "roll shot",
            "side roll",
            "func_969",
            "func_1082",
            "func_1083",
            "func_1085",
            "func_1086",
            "func_1088",
            "func_1089",
            "0x9940F95A",
            "0x2986D9F6",
            "0xF6FD193E",
            "func_1182",
            "func_873",
            "func_988",
            "func_849",
            "0x700000",
            "chrsysparam action matrix",
            "SUB_SHOT_FLIGHT_ROLL_L",
            "SUB_SHOT_FLIGHT_ROLL_R",
            "0x5346534c",
            "0x53465352",
        ),
        read_first=(R("hambrabi-flight-sub-side-roll-shot.md"),),
        related=(
            R("func593-vanilla-ranged-slots.md"),
            R("msc-generation-param-bridge-comparison.md"),
            R("2026-08-26-wing-zero-rebellion-subshot-split-and-flight-weapons-plan.md"),
            R("wing-zero-rebellion-unused-form-reload-group-b.md"),
        ),
        settled=(
            "Hambrabi is the external param-table generation: 0.c func_143 dispatches through sys_41 to a cmdaction row index, and 2.c func_849 walks sys_0(0x700001) registering every row via func_873 (kind -> ENTER) and func_988 (hash -> unit hook).",
            "The whole 2.c has only three func_593 ranged ENTERs (func_957 kind 0x03, func_963 kind 0x12, func_969 kind 0x35). They are shared archetypes; all behaviour values come from the row through func_875(row, field).",
            "E1 2026-09-01: 変形サブ射撃 is kind 0x03 rows 36/37/38 of chrsysparam.csyspm table0 (49x128, column = field+1), sharing func_1088 enter (0x7741FFF4) and func_1089 main (0xF2D67A5D). Row 36 0x9940F95A / row 37 0x2986D9F6 are the two 側転 sides; row 38 0xF6FD193E is 前後 前進射撃 and the only vertical-tracking variant. Kind 0x35 / func_969-974 is 変形特殊射撃 (フェダーイン), not this move.",
            "E1 2026-09-01: func_1082/1083/1085/1086 have zero chrsysparam row refs; they are dead code. func_1182 is only called from that dead pair. The live 3-chain is func_1089 re-seeking the clip to 8f at 23f and bumping global924, cap 3.",
            "The two roll sides differ only in the sign of sys_46(0x2, 0x3, +-0x2328, 0, 0xdc) and sys_46(0x1, 0x2, +-0x2328, ..., duration); global964 is the last-side latch that gates the reversal kick so same-side chaining does not stack it.",
            "func_873 and func_988 return raw bytecode pointers; resolve them against the sibling 2.txt [func_name, pointer] table with a fixed -48 offset.",
            "Wing Zero Rebellion is the classic local-selector generation with zero 0x700000 reads and a global779 ceiling, so the hooks cannot be cloned literally. Portable ENTER from func_1088 is analog mix 0x64/0x63/0x63 and global689=0x4; portable tick from func_1089 is the 7f sys_46 pair, 23f clip re-seek, and aim_budget-rationed yaw at 0x7d0.",
            "Ported 2026-08-31: bird global48 0x80 splits on global2 0x10/0x20 into homemade hashes 0x5346534c / 0x53465352 (SUB_SHOT_FLIGHT_ROLL), keep-form via the func_41 allowlist. 2026-09-01 E3: native global683=0x1. 2026-09-01 late: extras are func_1089 clip re-seek, not func_1182; E3 pending on the packed 2.dscex.",
            "E3 2026-09-01 (resolved): SHOOT-phase lock tracking must read the explicit target, sys_0(0x40000, 0x3, global39) behind the global39 != 0xffffffff and sys_0(0x70003, global39) guards, limited by func_102(diff, 0x1f4, 0x2), a per-frame angular speed cap. Holding any stick direction no longer steals the aim. Form is 002zgundm_001zgundm_001 func_1011 and this unit own rebellion_sub_shot_custom_aim.",
            "E3 2026-09-01: vertical aim is a registered bone-aim constraint, not per-frame pose code. func_594 calls func_616(global716) -> func_144, whose entire body sits behind if (global115 > 0), and global115 is only raised by func_142 / func_615. Without a registration func_144 is a no-op. func_144 emits sys_47(0x16, ...) to aim the bone at the target and sys_47(0x20, ...) to limit it with global322 / global323, then the engine maintains it, which is why Hambrabi has no per-frame vertical code. Fix is one line in START: func_615(0x1, 0xe, 0x8, 0), arguments from func_1082 / func_959; this unit already registers the same way in special_shot_flight_start.",
            "E1 2026-09-01: func_601 pitch branch is dead on every unit. Its gate is if (global720) and func_600 sets global720 = 0 on all three paths, so switching to the func_599 driver gains no vertical. func_599 can drive the existing quartet (func_600/601/602/603 are text-identical to Hambrabi) but that is a separate concern.",
            "E1 2026-09-01: global47 |= 0x40, which TV and Bound Doc set every tick, is func_283 time scaling. It skips sys_0(0x60010) / sys_0(0x60011) so the action runs at full speed. It is not an aim enable.",
            "E3 2026-09-01: func_595 is the only yaw writer in this action entire call closure and it runs only while global184 == 1, so SHOOT and END need their own per-frame tracking or the native owner takes the heading.",
            "Corpus 538 units: 7566 sys_46(0, ...) writes sit in phase bodies and callFunc3 ticks, 7243 of them as sys_46(0, VAR) right after a func_102 step. Per-frame yaw in a tick is normal (25.4 percent of ticks); a button read in a tick is not (11 of 26625).",
            "E3 2026-09-01: all three phases now run on the clip clock. START func_309(global20, 0x8 * 0x64) plus func_89(0x2fd, 0); SHOOT func_309(global20, sys_47(0x1, sys_4B(0x1)) - 0x1f4) or func_91(), which is func_972 verbatim; END func_91(), which is func_974.",
        ),
        do_not=(
            "Do not copy func_1082/1083/1085/1086 as 変形サブ射撃. E1 2026-09-01: those four have zero chrsysparam row refs (dead code). Live hooks are func_1088+func_1089 on kind 0x03 rows 36/37/38. They also read Hambrabi-only globals 951/952/964 above Rebellion's global779, so even the live pair cannot be registered literally.",
            "Do not treat kind 0x35 / func_969 as 変形サブ射撃; that row is 変形特殊射撃 (フェダーイン) and calls func_1179 to drop transform.",
            "Do not force extras with global683=0x3 (auto burst, ignores hold). Classic-selector units cannot call Hambrabi func_891 (0x700000). The live 3-chain is func_1089 clip re-seek, not func_1182 / func_81. Do not func_81(0x77b100ff) (A3).",
            "Do not treat func_957/963/969 as move-specific actions; they are kind archetypes shared by every row of that kind.",
            "I7: func_167 on this tick without a channel clamp is stick-follow. I12: motor-off without a clamp is free-fall. Stage 13 (E3 pending): SHOOT func_351(0,0x4) every tick plus Stage 12 last-writer clamp; 679 restores func_351(0x2,0x4) (D10). Skip 679 clamp. Do not sys_46(0xF). Do not clear 0x4000. Do not motor-off.",
            "Do not treat the sys_46 sign as a known left/right mapping; the axis convention is E0 and the port's sides may need swapping after an in-game run.",
            "Do not aim with sys_0(0x40000, 0x5) from a phase body or tick. E3- 2026-09-01: no observable change. It only appears inside func_626 / func_601 / func_595 and as 0.c func_97 fallback; the lock-target query is sys_0(0x40000, 0x3, global39).",
            "Do not chase vertical aim with per-frame pose code. E3- 2026-09-01, seven attempts, all no observable change because the mechanism was never enabled: func_105 add, func_104 set, pitch in the sys_46(0x1, 0x2) Y slot, the sys_46(0x1, 0x1) vertical channel (that one translates the unit downward and leaves it level), func_300 to func_301, zeroing pose layer B with func_107, and sys_4C(0x8, 0x3) with global183 = 0. A diagnostic swapping the roll clip for the bird loop stayed level too, so the clip is not the cause. Register the bone with func_615 instead.",
            "Do not diff two implementations line by line when a behaviour is missing entirely. The answer came from a full call-closure syscall diff (Hambrabi 153 functions / 84 distinct syscall+subcommand versus 84 / 60), which surfaced sys_4C(0x8) and from there the func_863 -> func_142 / func_144 register-then-apply pair.",
            "Do not chase heading drift with movement-side edits. E3- across stages 1-13: analog mix global452/453/454, func_351 profiles, func_296(0x3e9, 0) movement-owner decouple, sys_4C(0x8, 0x3) and the flight motor all produced no observable change. The fix was a correctly written yaw writer.",
            "Do not run func_296(0x3e8, 0) as a foot-stop in a bird-form action. E3 2026-09-01: it is the flight motor, and holding it off through SHOOT free-falls the unit while the form latch keeps the bird visuals.",
            "Do not switch the analog profile with func_351 inside this action. Hambrabi never calls it in flight because func_878 is gated on global24 0x2; the START 0x1 / SHOOT 0 / END 0x2 writes were TV and Messala leftovers and are removed, which also removes the cause of registry D10.",
            "Do not add a keep-form bird hash to only one allowlist. Rebellion has two mirrored lists: func_41 (global3 != ...) skips teardown, and func_882 (global3 == ...) early-returns before rebellion_interrupt_bird_form_to_ground + func_884. E3 2026-08-31: patching func_41 alone kept the flight loop motion while the unit lost the flight motor, the bird props and the bird weapon bar. Both lists must hold the same set.",
            "Do not edit 0.c for anything but input mapping (user rule 2026-08-31). 0.c owns which input selects which hash plus the four-value func_95 selector; behaviour, form, loadout and phases are 2.c. Read 0.c first, edit 2.c first: a 2.c fix on an action the input never reaches reads as no change.",
            "Do not hand-pick the four func_95 arguments. arg1 selects the pending queue (func_88 wants 0, and 0.c func_15 reads it to select the flight loop), arg3 is the input class index. Bird-form ranged actions use (0, 0x1, 0) like bird main / bird CS2 / flight special; (0x1, 0x1, 0x7) is the ground sub slot and routes into native func_15 -> func_882, which rebuilds the ground loadout.",
            "Do not expect TV func_351(0x1,0x4) alone on Rebellion roll-sub START/SHOOT ENTER to decouple translation from yaw. Runtime 2026-08-31 I9: no observable change. TV ALT_2/3 also uses a dedicated clip, func_168(0x1000000), func_166 pose and per-tick global47 0x40; copying only profile 1 is not the full TV recipe. Do not stack those extras in the same build.",
            "Do not increase or stack SHOOT yaw after Rebellion roll-sub I10. Do not retry mix, motor-off, SE, or 0x4000 clear. Stage 13 analog judgement is hold-back reverse during SHOOT on hash 1CFD3810 (profile 0 + last-writer clamp). Leaving profile 0 into EXIT is D10.",
        ),
    ),
    Cluster(
        id=CLUSTER_GYAN,
        title="Gyan MSC: melee, Dodai special shot, auto-turn",
        kind="unit",
        aliases=(
            "Gyan",
            "强人",
            "900000003",
            "005GYAN00",
            "001GUNDAM/005GYAN00",
            "0x35B195CC",
            "Dodai",
            "后格",
            "ACTION_B_MELEE_DIR_4",
            "0x58CC87CE",
            "DIR_2",
            "0xECE28FD9",
            "global693",
            "func_592",
            "func_495",
            "N2 rocket",
        ),
        read_first=(
            R("gyan-session-2026-07-11-handoff.md"),
            R("gyan-dodai-session-2026-07-10-handoff.md"),
        ),
        docs=(
            R("gyan-main-shot-no-auto-turn.md"),
            R("gyan-melee-direction-actions.md"),
            R("gyan-back-melee-movement.md"),
            R("gyan-dodai-special-shot-action-port.md"),
            R("gyan-dodai-throw-aim-at-enemy-analysis.md"),
        ),
        related=(
            R("units/2002001-hyaku-shiki/README.md"),
            "docs/characterparam-field-notes.md",
            "docs/param-editor-typed-labels-notes.md",
        ),
        settled=(
            "后格 = ACTION_B_MELEE_DIR_4 (0x58CC87CE); left/right melee is DIR_2 / motion 0xECE28FD9, not 后格.",
            "Main-shot auto-turn: global693 / func_592; flight uses global24 & 0x4000.",
            "Unit 900000003 Param folder trap: 0x35B195CC.",
        ),
    ),
    Cluster(
        id=CLUSTER_RX_78_2,
        title="1001001 RX-78-2 Gundam MSC",
        kind="unit",
        aliases=("RX-78-2", "1001001", "001GUNDAM", "Last Shooting", "Beam Javelin"),
        read_first=(R("units/1001001-rx-78-2/README.md"),),
        docs=(
            R("units/1001001-rx-78-2/legacy-1011-vs-ob-v27.md"),
            R("delta-plus-main-shot-rx78-style-auto-reload.md"),
        ),
    ),
    Cluster(
        id=CLUSTER_UNICORN,
        title="15001001 Unicorn Gundam MSC",
        kind="unit",
        aliases=("Unicorn", "15001001", "001UNIGUN", "NT-D", "Destroy mode"),
        read_first=(R("units/15001001-unicorn/README.md"),),
    ),
    Cluster(
        id=CLUSTER_KSHATRIYA,
        title="15002001 Kshatriya MSC",
        kind="unit",
        aliases=("Kshatriya", "15002001", "Besserung"),
        read_first=(R("units/15002001-kshatriya/README.md"),),
    ),
    Cluster(
        id=CLUSTER_SINANJU,
        title="15003001 Sinanju MSC",
        kind="unit",
        aliases=("Sinanju", "15003001", "Rozen Zulu", "Meteor Kick"),
        read_first=(R("units/15003001-sinanju/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DELTA_PLUS,
        title="15004001 Delta Plus / Waverider MSC",
        kind="unit",
        aliases=(
            "Delta Plus",
            "15004001",
            "004DELTPL",
            "Waverider",
            "0x04AD9F33",
            "0x5556A52B",
            "Jesta assist",
            "auto reload",
        ),
        read_first=(R("units/15004001-delta-plus/README.md"),),
        docs=(
            R("delta-plus-main-shot-rx78-style-auto-reload.md"),
            R("delta-plus-transform-flight-system.md"),
        ),
        settled=(
            "Official OB v27 evidence is 0x04AD9F33 + 0x5556A52B, not 0xBDBE6FEA.",
            "global143 on this unit is WR shell/loadout state.",
        ),
        do_not=(
            "Do not use the BDBE Delta Kai patched 2.c as vanilla Delta Plus.",
        ),
    ),
    Cluster(
        id=CLUSTER_DELTA_KAI,
        title="Delta Kai funnel / assist slot 2 (BDBE patched sample)",
        kind="unit",
        aliases=(
            "Delta Kai",
            "funnel",
            "slot 2",
            "0xBDBE6FEA",
            "transient CSA",
            "connect funnel",
        ),
        read_first=(R("delta-kai-funnel-assist-slot2.md"),),
        docs=(
            R("delta-kai-mod-design.md"),
            R("transient-csa-to-delta-kai-port-analysis.md"),
        ),
        settled=(
            "0xBDBE6FEA currently contains a 2026-06-19 Delta Kai AI patch; not official v27 Delta Plus.",
        ),
    ),
    Cluster(
        id=CLUSTER_HYAKU_SHIKI,
        title="2002001 Hyaku Shiki Dodai flight MSC",
        kind="unit",
        aliases=("Hyaku Shiki", "百式", "2002001", "002hyaksk", "0x43BB8719", "Dodai flight"),
        read_first=(R("units/2002001-hyaku-shiki/README.md"),),
        docs=(R("units/2002001-hyaku-shiki/motion-folder-bundle-structure.md"),),
        related=(R("units/2018001-dijeh/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DIJEH,
        title="2018001 Dijeh Dodai flight counterpart",
        kind="unit",
        aliases=("Dijeh", "迪杰", "2018001", "0x660B7580"),
        read_first=(R("units/2018001-dijeh/README.md"),),
        related=(R("units/2002001-hyaku-shiki/README.md"),),
    ),
    Cluster(
        id=CLUSTER_AGE_FX,
        title="33004001 Gundam AGE-FX MSC",
        kind="unit",
        aliases=("AGE-FX", "AGE FX", "33004001", "0x605245CC"),
        read_first=(R("units/33004001-age-fx/README.md"),),
    ),
    Cluster(
        id=CLUSTER_G_SELF,
        title="42001001 G-Self MSC",
        kind="unit",
        aliases=("G-Self", "G Self", "42001001", "Reflector", "Assault Pack"),
        read_first=(R("units/42001001-g-self/README.md"),),
    ),
    Cluster(
        id=CLUSTER_MACK_KNIFE,
        title="42002001 Mack Knife (Mask) MSC",
        kind="unit",
        aliases=("Mack Knife", "42002001", "Long-Range Booster", "Plasma Claw"),
        read_first=(R("units/42002001-mack-knife-mask/README.md"),),
    ),
    Cluster(
        id=CLUSTER_NEXA_N,
        title="59001001 NEXA-N MSC",
        kind="unit",
        aliases=("NEXA-N", "NEXA N", "59001001", "极限高达", "external Param action-table"),
        read_first=(R("units/59001001-nexa-n/README.md"),),
    ),
    Cluster(
        id=CLUSTER_AERIAL,
        title="66001001 Gundam Aerial MSC",
        kind="unit",
        aliases=("Aerial", "66001001", "Gundam Aerial"),
        read_first=(R("units/66001001-gundam-aerial/README.md"),),
    ),
    Cluster(
        id=CLUSTER_PHARACT,
        title="66002001 Gundam Pharact MSC",
        kind="unit",
        aliases=("Pharact", "66002001", "Corax", "Beakfoot"),
        read_first=(R("units/66002001-gundam-pharact/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DARILBALDE,
        title="66003001 Darilbalde MSC",
        kind="unit",
        aliases=("Darilbalde", "66003001", "Gusser Ishvara", "Daya Ambicar"),
        read_first=(R("units/66003001-darilbalde/README.md"),),
    ),
)


CLUSTER_BY_ID = {cluster.id: cluster for cluster in CLUSTERS}


# Printed on every --match. Routing already ranks the right cluster (audit F3),
# but a cluster's settled/do_not carries under half of the in-game-falsified
# results recorded in its owner note, so the negatives must be surfaced here too.
MANDATORY_READS = """\
=== read before proposing any MSC change ===
1 evidence grades + in-game audit protocol
  docs/msc-research/msc-evidence-grade-and-ingame-audit-protocol.md
2 falsified-negatives registry (grep your hash / func_N in it first)
  docs/msc-research/msc-falsified-negatives-registry.md
Reading X.c establishes E1 only. Behaviour claims need E3 (in-game).
============================================
"""


def owned_msc_research_paths(cluster: Cluster) -> set[str]:
    owned: set[str] = set()
    for path in cluster.read_first + cluster.docs:
        if path.startswith("docs/msc-research/") and not path.endswith("/INDEX.md"):
            owned.add(path)
    return owned


def on_disk_msc_research_paths() -> set[str]:
    paths: set[str] = set()
    for path in MSC_RESEARCH_DIR.rglob("*.md"):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel.endswith("/INDEX.md"):
            continue
        paths.add(rel)
    return paths


def score_cluster(cluster: Cluster, query: str) -> int:
    raw = query.strip().lower()
    if not raw:
        return 0
    tokens = [token for token in re.split(r"[\s,/|]+", raw) if token]
    haystack_parts = [
        cluster.id,
        cluster.id.replace("-", " "),
        cluster.title,
        cluster.kind,
        cluster.notes,
        " ".join(cluster.aliases),
        " ".join(cluster.settled),
        " ".join(Path(path).name for path in cluster.read_first + cluster.docs + cluster.related),
        " ".join(cluster.read_first + cluster.docs + cluster.related),
    ]
    haystack = "\n".join(haystack_parts).lower()
    score = 0
    if raw == cluster.id or raw == cluster.id.replace("-", " "):
        score += 100
    if raw in haystack:
        score += 40
    for token in tokens:
        if token == cluster.id or token == cluster.id.replace("-", " "):
            score += 20
        if any(token == alias.lower() or token in alias.lower() for alias in cluster.aliases):
            score += 12
        if token in haystack:
            score += 3
    return score


def match_clusters(query: str, limit: int = 5) -> list[tuple[int, Cluster]]:
    ranked = []
    for cluster in CLUSTERS:
        score = score_cluster(cluster, query)
        if score > 0:
            ranked.append((score, cluster))
    ranked.sort(key=lambda item: (-item[0], item[1].id))
    return ranked[:limit]


def format_cluster(cluster: Cluster) -> str:
    lines = [
        f"cluster: {cluster.id}",
        f"kind: {cluster.kind}",
        f"title: {cluster.title}",
        f"aliases: {' | '.join(cluster.aliases)}",
    ]
    if cluster.notes:
        lines.append(f"notes: {cluster.notes}")
    if cluster.settled:
        lines.append("settled:")
        lines.extend(f"- {item}" for item in cluster.settled)
    if cluster.read_first:
        lines.append("read_first:")
        lines.extend(f"- {path}" for path in cluster.read_first)
    if cluster.docs:
        lines.append("docs:")
        lines.extend(f"- {path}" for path in cluster.docs)
    if cluster.related:
        lines.append("related:")
        lines.extend(f"- {path}" for path in cluster.related)
    if cluster.do_not:
        lines.append("do_not:")
        lines.extend(f"- {item}" for item in cluster.do_not)
    return "\n".join(lines)


def render_index() -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "# MSC Research Cluster Index",
        "",
        "This file is the markdown projection of `tools/msc_research_catalog.py`.",
        "Do not edit it by hand. Register new MSC notes in the catalog, then run:",
        "",
        "```text",
        "python tools/msc_research_catalog.py --check",
        "python tools/msc_research_catalog.py --write-index",
        "```",
        "",
        "Agent routing skill: `.cursor/skills/msc-research-index/SKILL.md`",
        "Cursor rule: `.cursor/rules/msc-research-index.mdc`",
        "",
        "Query a cluster without listing the folder:",
        "",
        "```text",
        'python tools/msc_research_catalog.py --match "bird form func_143"',
        "```",
        "",
        "CodeGraph indexes the Python catalog (cluster ids and aliases), not the Markdown notes.",
        "Existing research notes are not rewritten by this index.",
        "",
        "## Clusters",
        "",
    ]
    for cluster in CLUSTERS:
        lines.append(f"### `{cluster.id}` — {cluster.title}")
        lines.append("")
        lines.append(f"- **kind:** {cluster.kind}")
        lines.append(f"- **aliases:** {', '.join(f'`{alias}`' for alias in cluster.aliases)}")
        if cluster.notes:
            lines.append(f"- **notes:** {cluster.notes}")
        if cluster.settled:
            lines.append("- **settled:**")
            lines.extend(f"  - {item}" for item in cluster.settled)
        if cluster.read_first:
            lines.append("- **read_first:**")
            lines.extend(f"  - `{path}`" for path in cluster.read_first)
        if cluster.docs:
            lines.append("- **docs:**")
            lines.extend(f"  - `{path}`" for path in cluster.docs)
        if cluster.related:
            lines.append("- **related:**")
            lines.extend(f"  - `{path}`" for path in cluster.related)
        if cluster.do_not:
            lines.append("- **do_not:**")
            lines.extend(f"  - {item}" for item in cluster.do_not)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def check_catalog() -> list[str]:
    errors: list[str] = []
    seen_ids: set[str] = set()
    for cluster in CLUSTERS:
        if cluster.id in seen_ids:
            errors.append(f"duplicate cluster id: {cluster.id}")
        seen_ids.add(cluster.id)
        if not cluster.read_first:
            errors.append(f"{cluster.id}: read_first is empty")
        for path in cluster.read_first + cluster.docs + cluster.related:
            disk = REPO_ROOT / path
            if not disk.exists():
                errors.append(f"{cluster.id}: missing path {path}")

    owned: set[str] = set()
    for cluster in CLUSTERS:
        owned |= owned_msc_research_paths(cluster)
    on_disk = on_disk_msc_research_paths()
    for path in sorted(on_disk - owned):
        errors.append(f"uncatalogued msc-research file: {path}")
    for path in sorted(owned - on_disk):
        errors.append(f"catalog path not on disk: {path}")

    if INDEX_PATH.exists():
        actual = INDEX_PATH.read_text(encoding="utf-8")
        expected = render_index()
        if actual != expected:
            errors.append(
                "docs/msc-research/INDEX.md is stale; run "
                "python tools/msc_research_catalog.py --write-index"
            )
    else:
        errors.append("docs/msc-research/INDEX.md is missing; run --write-index")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = ArgumentParser(description="Route MSC research notes by cluster.")
    parser.add_argument("--list", action="store_true", help="List cluster ids")
    parser.add_argument("--match", metavar="QUERY", help="Rank clusters for a task query")
    parser.add_argument("--print", dest="print_id", metavar="CLUSTER", help="Print one cluster")
    parser.add_argument("--check", action="store_true", help="Validate catalog coverage")
    parser.add_argument("--write-index", action="store_true", help="Write docs/msc-research/INDEX.md")
    parser.add_argument("--limit", type=int, default=5, help="Max --match hits")
    args = parser.parse_args(argv)

    selected = [
        bool(args.list),
        bool(args.match),
        bool(args.print_id),
        bool(args.check),
        bool(args.write_index),
    ]
    if sum(selected) != 1:
        parser.error("choose exactly one of --list / --match / --print / --check / --write-index")

    if args.list:
        for cluster in CLUSTERS:
            print(f"{cluster.id}\t{cluster.kind}\t{cluster.title}")
        return 0

    if args.print_id:
        cluster = CLUSTER_BY_ID.get(args.print_id)
        if cluster is None:
            print(f"unknown cluster: {args.print_id}", file=sys.stderr)
            print("known:", ", ".join(CLUSTER_BY_ID), file=sys.stderr)
            return 1
        print(format_cluster(cluster))
        return 0

    if args.match:
        ranked = match_clusters(args.match, limit=args.limit)
        if not ranked:
            print(MANDATORY_READS)
            print("no cluster matched")
            print("known:")
            for cluster in CLUSTERS:
                print(f"- {cluster.id}: {cluster.title}")
            return 1
        print(MANDATORY_READS)
        print("matches:")
        for score, cluster in ranked:
            print(f"- {cluster.id} ({score}) {cluster.title}")
        print("---")
        print(format_cluster(ranked[0][1]))
        if len(ranked) > 1 and ranked[1][0] >= max(12, ranked[0][0] // 3):
            print("---")
            print(format_cluster(ranked[1][1]))
        return 0

    if args.write_index:
        INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        INDEX_PATH.write_text(render_index(), encoding="utf-8", newline="\n")
        print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT).as_posix()}")
        return 0

    errors = check_catalog()
    if errors:
        for error in errors:
            print(error)
        return 1
    print(
        f"OK: {len(CLUSTERS)} clusters, "
        f"{len(on_disk_msc_research_paths())} msc-research files catalogued"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
