"""MSC research cluster catalog.

Canonical index for docs/msc-research and related MSC notes.

CodeGraph indexes this Python module (cluster ids, aliases, paths). Markdown
research notes are not in the graph; agents must match a cluster here instead
of listing docs/msc-research.

Query:
    python tools/msc_research_catalog.py --match "bird form func_143"
    python tools/msc_research_catalog.py --print wing-zero-rebellion
    python tools/msc_research_catalog.py --list
    python tools/msc_research_catalog.py --check
    python tools/msc_research_catalog.py --write-index
"""

from __future__ import annotations

from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
import re
import sys


REPO_ROOT = Path(__file__).resolve().parent.parent
MSC_RESEARCH_DIR = REPO_ROOT / "docs" / "msc-research"
INDEX_PATH = MSC_RESEARCH_DIR / "INDEX.md"
GENERATED_BANNER = (
    "<!-- Generated by tools/msc_research_catalog.py. Do not edit by hand. -->"
)


def R(*parts: str) -> str:
    return "/".join(("docs/msc-research",) + parts)


# Cluster ids as named constants so CodeGraph / rg can find them.
CLUSTER_META = "meta"
CLUSTER_TOOLCHAIN = "toolchain"
CLUSTER_SYSCALL = "syscall"
CLUSTER_RUNTIME_2C = "runtime-2c"
CLUSTER_INPUT_0C = "input-0c"
CLUSTER_MODDING = "modding"
CLUSTER_MOVEMENT = "movement"
CLUSTER_RANGED = "ranged"
CLUSTER_REGISTRY = "registry"
CLUSTER_CROSS_UNIT = "cross-unit"
CLUSTER_PARAM_MSC = "param-msc"
CLUSTER_NATIVE_UNIT_TASK = "native-unit-task"
CLUSTER_CHARGE = "charge"
CLUSTER_WING_ZERO_REBELLION = "wing-zero-rebellion"
CLUSTER_WING_ZERO_TV = "wing-zero-tv"
CLUSTER_GYAN = "gyan"
CLUSTER_RX_78_2 = "unit-rx-78-2"
CLUSTER_UNICORN = "unit-unicorn"
CLUSTER_KSHATRIYA = "unit-kshatriya"
CLUSTER_SINANJU = "unit-sinanju"
CLUSTER_DELTA_PLUS = "unit-delta-plus"
CLUSTER_DELTA_KAI = "unit-delta-kai"
CLUSTER_HYAKU_SHIKI = "unit-hyaku-shiki"
CLUSTER_DIJEH = "unit-dijeh"
CLUSTER_AGE_FX = "unit-age-fx"
CLUSTER_G_SELF = "unit-g-self"
CLUSTER_MACK_KNIFE = "unit-mack-knife"
CLUSTER_NEXA_N = "unit-nexa-n"
CLUSTER_AERIAL = "unit-aerial"
CLUSTER_PHARACT = "unit-pharact"
CLUSTER_DARILBALDE = "unit-darilbalde"


@dataclass(frozen=True)
class Cluster:
    id: str
    title: str
    kind: str
    aliases: tuple[str, ...]
    read_first: tuple[str, ...]
    docs: tuple[str, ...] = ()
    related: tuple[str, ...] = ()
    settled: tuple[str, ...] = ()
    do_not: tuple[str, ...] = ()
    notes: str = ""


CLUSTERS: tuple[Cluster, ...] = (
    Cluster(
        id=CLUSTER_META,
        title="MSC research folder meta / coverage",
        kind="global",
        aliases=(
            "msc-research README",
            "gap map",
            "notion msc",
            "msc research summary",
            "docs/msc-research",
        ),
        read_first=(R("INDEX.md"), R("README.md")),
        docs=(
            R("msc-research-gap-map.md"),
            R("notion-msc-cross-reference.md"),
            R("20260621-215819-msc-research-summary.md"),
        ),
        notes="Human README remains; INDEX.md is the cluster projection of this catalog.",
    ),
    Cluster(
        id=CLUSTER_TOOLCHAIN,
        title="MSC format, decompile, repack, AI edit blocks",
        kind="toolchain",
        aliases=(
            "mscdec",
            "msclang",
            "mscsb",
            "bscex",
            "cscex",
            "dscex",
            "pushBit",
            "AI decision",
            "opaque func ptr",
            "0x5fef",
            "func_143 offset",
            "auto rename",
            "ACTION_* naming",
            "repack crash",
            "msc_core.py",
            "msc_cfg.py",
        ),
        read_first=(
            "docs/msc-binary-format-spec.md",
            R("msc-ai-edit-block-rule.md"),
            R("msc-repack-runnable-guide.md"),
        ),
        docs=(
            R("msc-auto-rename-mapping.md"),
        ),
        related=(
            "docs/exvs2-msc-vm-native-semantics.md",
            "docs/exvs-msc-analysis.md",
            "docs/msc-system-problems-analysis.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
            "docs/agent-sessions/2026-08-03-traditional-msc-workspace.md",
            "docs/agent-sessions/msc-workspace-redesign/plan.md",
            "docs/agent-sessions/msc-human-roundtrip/process.md",
            "docs/agent-sessions/mscdec-log-regression-fix/session.md",
            "tools/check_msc_ai_blocks.py",
            "tools/check_msc_opaque_func_ptrs.py",
        ),
        settled=(
            "Game repack uses tools/msclang.py; msclang_modern.py is research-only.",
            "MSC headers are LE; script-body opcode parameters are BE.",
            "Function pointers in 0.c/2.c must be symbols (func_143), never raw offsets like 0x5fef.",
            "AI-edited X.c blocks need // AI decision and // End, origin is ... pairs.",
            "AI-block comments explain original global/func/sys traps; do not restate AI semantic names.",
        ),
        do_not=(
            "Do not invent global777/var42 names for AI-added MSC state.",
            "Do not write AI-block comments that only narrate AI semantic names.",
            "Do not use generated analysis JSON / overlays as evidence.",
        ),
    ),
    Cluster(
        id=CLUSTER_SYSCALL,
        title="Native MSC syscall notes",
        kind="global",
        aliases=(
            "sys_46",
            "sys_4F",
            "sys_4E",
            "sys_4B",
            "sys_47",
            "sys_51",
            "sys_53",
            "sys_54",
            "sys_55",
            "syscall",
            "sys_0",
        ),
        read_first=(
            "docs/exvs-msc-syscall-4f-native-handler.md",
            "docs/exvs-msc-syscall-4f-notes.md",
            R("sys46-script-parameter-atlas.md"),
        ),
        related=(
            "docs/exvs-msc-syscall-47-notes.md",
            "docs/exvs-msc-syscall-4b-notes.md",
            "docs/exvs-msc-syscall-4e-notes.md",
            "docs/exvs-msc-syscall-53-notes.md",
            "docs/exvs-msc-syscall-54-notes.md",
            "docs/exvs-msc-syscall-55-notes.md",
            "docs/exvs-native-truth-mapping-workflow.md",
            "docs/exvs-native-truth-verification.md",
        ),
        notes="Syscall notes live under docs/, not docs/msc-research/.",
    ),
    Cluster(
        id=CLUSTER_RUNTIME_2C,
        title="Global 2.c runtime / action depiction architecture",
        kind="global",
        aliases=(
            "2.c",
            "func_1",
            "func_4",
            "func_44",
            "func_52",
            "func_877",
            "func_1042",
            "func_1043",
            "ACTION_*",
            "depiction",
            "2c whole file",
            "frame lifecycle",
            "action registry",
        ),
        read_first=(
            R("2c-first-hour-source-reading-roadmap.md"),
            R("msc-modder-operating-manual.md"),
        ),
        docs=(
            R("2c-source-proof-walkthrough-for-modders.md"),
            R("2c-entry-to-action-output-walkthrough.md"),
            R("2c-call-chain-runtime-flow.md"),
            R("2c-frame-lifecycle-human-trace.md"),
            R("2c-runtime-system-map-for-modding.md"),
            R("2c-whole-file-map.md"),
            R("2c-function-clusters.md"),
            R("2c-function-role-map-for-modders.md"),
            R("2c-function-responsibility-proof-handbook.md"),
            R("2c-human-readable-modding-field-guide.md"),
            R("2c-key-function-atlas-for-patching.md"),
        ),
        settled=(
            "2.c is depiction output, not the input selector.",
            "main -> func_1 -> func_877 -> func_1042/1043 -> func_4 -> func_44/52 -> ACTION_* -> syscall.",
            "Find an action from func_1043, not from func_887/888.",
        ),
        do_not=(
            "Do not treat 2.c as original C source; it is decompiled MSC.",
            "Do not start a 2.c patch at shell loadout unless the goal is shell/loadout.",
        ),
    ),
    Cluster(
        id=CLUSTER_CHARGE,
        title="CS charge-slot consumption at action entry",
        kind="global",
        aliases=(
            "CSA",
            "CSB",
            "charge slot",
            "charge consume",
            "charge reset",
            "sys_4F(0xA)",
            "ACTION_CHARGE_SHOT",
            "ACTION_MASK_1000",
            "0x800",
            "0x1000",
            "infinite charge shot",
        ),
        read_first=(
            R("cs-action-charge-slot-consumption.md"),
        ),
        related=(
            "docs/exvs-msc-syscall-4f-native-handler.md",
            R("wing-zero-rebellion-bird-form-0c-input-map.md"),
        ),
        settled=(
            "A selected CS action must consume/reset its native charge slot once at action entry.",
            "Direct CSA on slot 0 uses sys_4F(0xA, 0); Rebellion CSB slot 4 is already consumed by func_1031.",
            "Do not put CSA charge clearing in an uncharged action alias or a per-tick callback.",
        ),
        do_not=(
            "Do not assume selecting or playing a CS action automatically consumes native charge state.",
            "Do not delay charge consumption until projectile fire; an interrupted startup would preserve a reusable full charge.",
        ),
    ),
    Cluster(
        id=CLUSTER_INPUT_0C,
        title="0.c input selector to 2.c action hash boundary",
        kind="global",
        aliases=(
            "0.c",
            "func_143",
            "func_95",
            "input bit",
            "action hash",
            "pending action",
            "thinker",
            "0c to 2c",
        ),
        read_first=(R("0c-to-2c-input-action-boundary.md"),),
        related=(
            "docs/exvs-msc-input-action-weapon-pipeline.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
        ),
        settled=(
            "Player buttons are selected in 0.c func_143, then consumed by 2.c ACTION_*.",
            "Input-bit meaning is unit-specific; do not copy TV bits onto Rebellion.",
        ),
    ),
    Cluster(
        id=CLUSTER_MODDING,
        title="Global MSC modding manuals and control surfaces",
        kind="global",
        aliases=(
            "modder",
            "cookbook",
            "system cards",
            "control surface",
            "patch point",
            "worked traces",
            "operating manual",
            "speed_param vs script",
        ),
        read_first=(
            R("msc-modder-operating-manual.md"),
            R("system-control-surface-matrix.md"),
            R("modding-decision-tree-system-cards.md"),
        ),
        docs=(
            R("modder-human-flow-overview.md"),
            R("modder-practical-callchain-guide.md"),
            R("modder-worked-traces.md"),
            R("modding-cookbook-action-editing.md"),
            R("modding-system-cards-handbook.md"),
            R("modding-walkthroughs-action-to-patch-points.md"),
            R("resource-control-surface-for-modders.md"),
        ),
    ),
    Cluster(
        id=CLUSTER_MOVEMENT,
        title="BD / boost / sys_46 / func_11 movement",
        kind="global",
        aliases=(
            "BD",
            "boost dash",
            "step",
            "sys_46",
            "func_11",
            "0xc000",
            "boost gate",
            "global23",
            "speedparam movement",
        ),
        read_first=(
            R("movement-bd-modding-workbook.md"),
            R("movement-boost-sys46-func11-map.md"),
        ),
        docs=(
            R("sys46-script-parameter-atlas.md"),
            R("func11-c000-boost-gate-map.md"),
        ),
        settled=(
            "Ordinary BD/step is mostly speed_param + 0.c, not a 2.c ACTION_* authoring job.",
        ),
    ),
    Cluster(
        id=CLUSTER_RANGED,
        title="func_593 vanilla ranged quartet",
        kind="global",
        aliases=(
            "func_593",
            "func_587",
            "global676",
            "global677",
            "global678",
            "global679",
            "global680",
            "no-ammo",
            "ranged slots",
            "start shoot end",
        ),
        read_first=(R("func593-vanilla-ranged-slots.md"),),
        settled=(
            "func_593 quartet: 676 start, 677 shoot, 678 no-ammo (not cancel), 679 end.",
            "func_587 main shot uses 677+680 fire; do not mix with the 593 quartet.",
        ),
        do_not=(
            "Do not treat 678 as cancel.",
        ),
    ),
    Cluster(
        id=CLUSTER_REGISTRY,
        title="Action/slot registry and shell loadout",
        kind="global",
        aliases=(
            "func_1044",
            "func_887",
            "func_888",
            "shell loadout",
            "slot callback",
            "global170",
            "global143",
            "sys_4B",
        ),
        read_first=(
            R("func1044-slot-callback-atlas.md"),
            R("shell-loadout-func-887-888.md"),
        ),
        docs=(R("func1044-simulated-renames.md"),),
        related=("docs/exvs-msc-func-887-888-shell-loadout-notes.md",),
        settled=(
            "func_887 selects default shell loadout; it is not the whole transform system.",
            "global143 meaning is unit-specific (WR flag on Delta Plus, form/shell on others).",
        ),
    ),
    Cluster(
        id=CLUSTER_CROSS_UNIT,
        title="Cross-unit MSC generation and Param action bridge",
        kind="global",
        aliases=(
            "cross-unit",
            "classic local selector",
            "external Param action-table",
            "legacy B4AC",
            "chrsysparam",
            "generation bridge",
        ),
        read_first=(
            R("cross-unit-msc-research-overview.md"),
            R("msc-generation-param-bridge-comparison.md"),
        ),
        docs=(R("cross-unit-first-batch-comparison.md"),),
        settled=(
            "Unit pages under docs/msc-research/units/<id>-<slug>/ are the per-unit homes.",
            "Do not use 0xBDBE6FEA as official OB v27 Delta Plus evidence.",
        ),
    ),
    Cluster(
        id=CLUSTER_PARAM_MSC,
        title="Param tables consumed by MSC / native",
        kind="global",
        aliases=(
            "speedparam",
            "characterparam",
            "armsparam",
            "bulletparam",
            "sys_0 0x60006",
            "lock-on",
            "red lock",
            "param evidence",
        ),
        read_first=(
            "docs/param-table-id-file-binding-proof.md",
            "docs/speedparam-msc-consumer-evidence.md",
            "docs/lock-on-range-native-resolution-ob.md",
        ),
        related=(
            "docs/speedparam-msc-consumer-audit.md",
            "docs/characterparam-native-consumer-map-ob.md",
            "docs/characterparam-field-notes.md",
            "docs/param-evidence-registry.tsv",
            "docs/param-editor-typed-labels-notes.md",
        ),
        settled=(
            "sys_0 table 0x60006=speedparam, 0x60002=grapparam, 0x60007=interactionid.",
            "Red-lock is min(Family1, Family2*scale+offset-1); no single characterparam field owns it.",
        ),
        do_not=(
            "Do not treat docs/command_mapping.md or speedparam-semantic-ledger.md as current truth.",
        ),
    ),
    Cluster(
        id=CLUSTER_NATIVE_UNIT_TASK,
        title="Native unit-task automata (not MSC 0.c/2.c)",
        kind="global",
        aliases=(
            "unit-task",
            "automata",
            "summon",
            "throwshield",
            "hammershot",
            "vtable",
        ),
        read_first=(
            "docs/unit-task-automata-deep-analysis.md",
            "docs/unit-task-automata-process.md",
        ),
        related=(
            "docs/unit-task-automata-decompiled-analysis.md",
            "docs/unit-task-automata-ida-analysis.md",
            "docs/unit-task-automata-execute-analysis.md",
            "docs/unit-task-automata-spawn-trace.md",
            "docs/unit-task-automata-summon-analysis.md",
            "docs/unit-task-automata-vtable-reference.md",
            "docs/001gundam-throwshield-hammershot-analysis.md",
        ),
        notes="Native C++ unit-task layer. Do not route these questions into 2.c ACTION_* first.",
    ),
    Cluster(
        id=CLUSTER_WING_ZERO_REBELLION,
        title="Wing Zero Rebellion MSC / bird-form transform port",
        kind="unit",
        aliases=(
            "Wing Gundam Zero Rebellion",
            "wing_gundam_zero_rebellion",
            "900000004",
            "kamaesht2neo",
            "Neo Bird",
            "bird form",
            "鸟形态",
            "飞翼零式叛乱",
            "零式叛乱",
            "Rebellion",
            "FORCED_RECOVERY",
            "0x77b100ff",
            "alt2 gerobi",
            "N特射",
            "SUB_SHOT_CUSTOM",
            "rebellion_hiv_lock_aim",
            "0x7cd11119",
            "0x928ca34f",
            "func_937",
            "bird melee",
            "鸟近战",
        ),
        read_first=(
            "docs/agent-sessions/2026-08-09-wing-zero-rebellion-transform-handoff.md",
            R("wing-zero-rebellion-bird-form-0c-input-map.md"),
            R("wing-zero-rebellion-flight-interrupt-form.md"),
        ),
        docs=(
            R("2026-08-09-wing-zero-rebellion-transform-port-plan.md"),
            R("alt2-gerobi-stop-and-followup.md"),
            R("sub-shot-custom-start-only-aim.md"),
            R("wing-zero-rebellion-bird-melee-n-followup.md"),
        ),
        related=(
            R("tv-wing-zero-flight-double-forward-aim.md"),
            R("tv-wing-zero-flight-special-melee-landing-copy-list.md"),
            R("tv-wing-zero-flight-special-melee-landing-todo.md"),
            R("func593-vanilla-ranged-slots.md"),
            "work/20260809-wing-zero-rebellion-transform-plan/evidence/E-007.md",
            "work/20260809-wing-zero-rebellion-transform-plan/evidence/E-008.md",
            "docs/agent-sessions/2026-08-13-msc-0c-function-pointer-offset-bug.md",
            "docs/agent-sessions/2026-08-23-wing-zero-flight-special-melee-debug.md",
        ),
        settled=(
            "Bird arsenal is gated in 0.c func_143 only, not 2.c ACTION_*.",
            "Rebellion main-shot bit is 0x1 (not TV 0x100); bird form id is 0x2 (TV 0x1).",
            "Bird melee 0x2 maps to 0x928ca34f (special-melee N followup func_937); do not split 0x8b97920e; do not add that hash to the func_41 flight allowlist; do not copy Delta Plus func_888(0x8) model switch.",
            "Hit/interrupt is FORCED_RECOVERY; do not requeue 0x77b100ff.",
            "Action hash is not form; form lives in global143.",
            "Do not tear form only on standing idle 0x6d00aeaa.",
            "678 is no-ammo, not cancel.",
            "Locate resources by canonical names, never by package hash.",
        ),
        do_not=(
            "Do not unpack FHM2D for this case; named sources already exist.",
            "Do not reopen the legacy '85 model assets missing' hash manifests.",
            "Do not mix transform-port notes with alt2 gerobi followup, SUB_SHOT_CUSTOM aim, or bird N melee 0x928ca34f.",
            "Do not mix bird N melee 0x928ca34f with TV bird special-melee landing hashes.",
            "Do not restart from package discovery unless a bootstrap restart condition is met.",
        ),
        notes="AGENTS.md still inlines this bootstrap. Sibling Rebellion MSC edits: alt2-gerobi, sub-shot-custom, bird-melee-n-followup.",
    ),
    Cluster(
        id=CLUSTER_WING_ZERO_TV,
        title="TV Wing Zero source behavior for the Rebellion port",
        kind="unit",
        aliases=(
            "TV Wing Zero",
            "28001001",
            "028gunwtv_001gunwtv_001",
            "028gunwtv",
            "TV Zero",
            "special melee landing",
            "double forward aim",
        ),
        read_first=(
            R("tv-wing-zero-flight-double-forward-aim.md"),
            R("tv-wing-zero-flight-special-melee-landing-copy-list.md"),
        ),
        docs=(R("tv-wing-zero-flight-special-melee-landing-todo.md"),),
        related=(
            "docs/agent-sessions/2026-08-09-wing-zero-rebellion-transform-handoff.md",
        ),
        do_not=(
            "Do not copy TV input bits or TV interrupt requeue onto Rebellion as-is.",
        ),
    ),
    Cluster(
        id=CLUSTER_GYAN,
        title="Gyan MSC: melee, Dodai special shot, auto-turn",
        kind="unit",
        aliases=(
            "Gyan",
            "强人",
            "900000003",
            "005GYAN00",
            "001GUNDAM/005GYAN00",
            "0x35B195CC",
            "Dodai",
            "后格",
            "ACTION_B_MELEE_DIR_4",
            "0x58CC87CE",
            "DIR_2",
            "0xECE28FD9",
            "global693",
            "func_592",
            "func_495",
            "N2 rocket",
        ),
        read_first=(
            R("gyan-session-2026-07-11-handoff.md"),
            R("gyan-dodai-session-2026-07-10-handoff.md"),
        ),
        docs=(
            R("gyan-main-shot-no-auto-turn.md"),
            R("gyan-melee-direction-actions.md"),
            R("gyan-back-melee-movement.md"),
            R("gyan-dodai-special-shot-action-port.md"),
            R("gyan-dodai-throw-aim-at-enemy-analysis.md"),
        ),
        related=(
            R("units/2002001-hyaku-shiki/README.md"),
            "docs/characterparam-field-notes.md",
            "docs/param-editor-typed-labels-notes.md",
        ),
        settled=(
            "后格 = ACTION_B_MELEE_DIR_4 (0x58CC87CE); left/right melee is DIR_2 / motion 0xECE28FD9, not 后格.",
            "Main-shot auto-turn: global693 / func_592; flight uses global24 & 0x4000.",
            "Unit 900000003 Param folder trap: 0x35B195CC.",
        ),
    ),
    Cluster(
        id=CLUSTER_RX_78_2,
        title="1001001 RX-78-2 Gundam MSC",
        kind="unit",
        aliases=("RX-78-2", "1001001", "001GUNDAM", "Last Shooting", "Beam Javelin"),
        read_first=(R("units/1001001-rx-78-2/README.md"),),
        docs=(
            R("units/1001001-rx-78-2/legacy-1011-vs-ob-v27.md"),
            R("delta-plus-main-shot-rx78-style-auto-reload.md"),
        ),
    ),
    Cluster(
        id=CLUSTER_UNICORN,
        title="15001001 Unicorn Gundam MSC",
        kind="unit",
        aliases=("Unicorn", "15001001", "001UNIGUN", "NT-D", "Destroy mode"),
        read_first=(R("units/15001001-unicorn/README.md"),),
    ),
    Cluster(
        id=CLUSTER_KSHATRIYA,
        title="15002001 Kshatriya MSC",
        kind="unit",
        aliases=("Kshatriya", "15002001", "Besserung"),
        read_first=(R("units/15002001-kshatriya/README.md"),),
    ),
    Cluster(
        id=CLUSTER_SINANJU,
        title="15003001 Sinanju MSC",
        kind="unit",
        aliases=("Sinanju", "15003001", "Rozen Zulu", "Meteor Kick"),
        read_first=(R("units/15003001-sinanju/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DELTA_PLUS,
        title="15004001 Delta Plus / Waverider MSC",
        kind="unit",
        aliases=(
            "Delta Plus",
            "15004001",
            "004DELTPL",
            "Waverider",
            "0x04AD9F33",
            "0x5556A52B",
            "Jesta assist",
            "auto reload",
        ),
        read_first=(R("units/15004001-delta-plus/README.md"),),
        docs=(
            R("delta-plus-main-shot-rx78-style-auto-reload.md"),
            R("delta-plus-transform-flight-system.md"),
        ),
        settled=(
            "Official OB v27 evidence is 0x04AD9F33 + 0x5556A52B, not 0xBDBE6FEA.",
            "global143 on this unit is WR shell/loadout state.",
        ),
        do_not=(
            "Do not use the BDBE Delta Kai patched 2.c as vanilla Delta Plus.",
        ),
    ),
    Cluster(
        id=CLUSTER_DELTA_KAI,
        title="Delta Kai funnel / assist slot 2 (BDBE patched sample)",
        kind="unit",
        aliases=(
            "Delta Kai",
            "funnel",
            "slot 2",
            "0xBDBE6FEA",
            "transient CSA",
            "connect funnel",
        ),
        read_first=(R("delta-kai-funnel-assist-slot2.md"),),
        docs=(
            R("delta-kai-mod-design.md"),
            R("transient-csa-to-delta-kai-port-analysis.md"),
        ),
        settled=(
            "0xBDBE6FEA currently contains a 2026-06-19 Delta Kai AI patch; not official v27 Delta Plus.",
        ),
    ),
    Cluster(
        id=CLUSTER_HYAKU_SHIKI,
        title="2002001 Hyaku Shiki Dodai flight MSC",
        kind="unit",
        aliases=("Hyaku Shiki", "百式", "2002001", "002hyaksk", "0x43BB8719", "Dodai flight"),
        read_first=(R("units/2002001-hyaku-shiki/README.md"),),
        docs=(R("units/2002001-hyaku-shiki/motion-folder-bundle-structure.md"),),
        related=(R("units/2018001-dijeh/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DIJEH,
        title="2018001 Dijeh Dodai flight counterpart",
        kind="unit",
        aliases=("Dijeh", "迪杰", "2018001", "0x660B7580"),
        read_first=(R("units/2018001-dijeh/README.md"),),
        related=(R("units/2002001-hyaku-shiki/README.md"),),
    ),
    Cluster(
        id=CLUSTER_AGE_FX,
        title="33004001 Gundam AGE-FX MSC",
        kind="unit",
        aliases=("AGE-FX", "AGE FX", "33004001", "0x605245CC"),
        read_first=(R("units/33004001-age-fx/README.md"),),
    ),
    Cluster(
        id=CLUSTER_G_SELF,
        title="42001001 G-Self MSC",
        kind="unit",
        aliases=("G-Self", "G Self", "42001001", "Reflector", "Assault Pack"),
        read_first=(R("units/42001001-g-self/README.md"),),
    ),
    Cluster(
        id=CLUSTER_MACK_KNIFE,
        title="42002001 Mack Knife (Mask) MSC",
        kind="unit",
        aliases=("Mack Knife", "42002001", "Long-Range Booster", "Plasma Claw"),
        read_first=(R("units/42002001-mack-knife-mask/README.md"),),
    ),
    Cluster(
        id=CLUSTER_NEXA_N,
        title="59001001 NEXA-N MSC",
        kind="unit",
        aliases=("NEXA-N", "NEXA N", "59001001", "极限高达", "external Param action-table"),
        read_first=(R("units/59001001-nexa-n/README.md"),),
    ),
    Cluster(
        id=CLUSTER_AERIAL,
        title="66001001 Gundam Aerial MSC",
        kind="unit",
        aliases=("Aerial", "66001001", "Gundam Aerial"),
        read_first=(R("units/66001001-gundam-aerial/README.md"),),
    ),
    Cluster(
        id=CLUSTER_PHARACT,
        title="66002001 Gundam Pharact MSC",
        kind="unit",
        aliases=("Pharact", "66002001", "Corax", "Beakfoot"),
        read_first=(R("units/66002001-gundam-pharact/README.md"),),
    ),
    Cluster(
        id=CLUSTER_DARILBALDE,
        title="66003001 Darilbalde MSC",
        kind="unit",
        aliases=("Darilbalde", "66003001", "Gusser Ishvara", "Daya Ambicar"),
        read_first=(R("units/66003001-darilbalde/README.md"),),
    ),
)


CLUSTER_BY_ID = {cluster.id: cluster for cluster in CLUSTERS}


def owned_msc_research_paths(cluster: Cluster) -> set[str]:
    owned: set[str] = set()
    for path in cluster.read_first + cluster.docs:
        if path.startswith("docs/msc-research/") and not path.endswith("/INDEX.md"):
            owned.add(path)
    return owned


def on_disk_msc_research_paths() -> set[str]:
    paths: set[str] = set()
    for path in MSC_RESEARCH_DIR.rglob("*.md"):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel.endswith("/INDEX.md"):
            continue
        paths.add(rel)
    return paths


def score_cluster(cluster: Cluster, query: str) -> int:
    raw = query.strip().lower()
    if not raw:
        return 0
    tokens = [token for token in re.split(r"[\s,/|]+", raw) if token]
    haystack_parts = [
        cluster.id,
        cluster.id.replace("-", " "),
        cluster.title,
        cluster.kind,
        cluster.notes,
        " ".join(cluster.aliases),
        " ".join(cluster.settled),
        " ".join(Path(path).name for path in cluster.read_first + cluster.docs + cluster.related),
        " ".join(cluster.read_first + cluster.docs + cluster.related),
    ]
    haystack = "\n".join(haystack_parts).lower()
    score = 0
    if raw == cluster.id or raw == cluster.id.replace("-", " "):
        score += 100
    if raw in haystack:
        score += 40
    for token in tokens:
        if token == cluster.id or token == cluster.id.replace("-", " "):
            score += 20
        if any(token == alias.lower() or token in alias.lower() for alias in cluster.aliases):
            score += 12
        if token in haystack:
            score += 3
    return score


def match_clusters(query: str, limit: int = 5) -> list[tuple[int, Cluster]]:
    ranked = []
    for cluster in CLUSTERS:
        score = score_cluster(cluster, query)
        if score > 0:
            ranked.append((score, cluster))
    ranked.sort(key=lambda item: (-item[0], item[1].id))
    return ranked[:limit]


def format_cluster(cluster: Cluster) -> str:
    lines = [
        f"cluster: {cluster.id}",
        f"kind: {cluster.kind}",
        f"title: {cluster.title}",
        f"aliases: {' | '.join(cluster.aliases)}",
    ]
    if cluster.notes:
        lines.append(f"notes: {cluster.notes}")
    if cluster.settled:
        lines.append("settled:")
        lines.extend(f"- {item}" for item in cluster.settled)
    if cluster.read_first:
        lines.append("read_first:")
        lines.extend(f"- {path}" for path in cluster.read_first)
    if cluster.docs:
        lines.append("docs:")
        lines.extend(f"- {path}" for path in cluster.docs)
    if cluster.related:
        lines.append("related:")
        lines.extend(f"- {path}" for path in cluster.related)
    if cluster.do_not:
        lines.append("do_not:")
        lines.extend(f"- {item}" for item in cluster.do_not)
    return "\n".join(lines)


def render_index() -> str:
    lines = [
        GENERATED_BANNER,
        "",
        "# MSC Research Cluster Index",
        "",
        "This file is the markdown projection of `tools/msc_research_catalog.py`.",
        "Do not edit it by hand. Register new MSC notes in the catalog, then run:",
        "",
        "```text",
        "python tools/msc_research_catalog.py --check",
        "python tools/msc_research_catalog.py --write-index",
        "```",
        "",
        "Agent routing skill: `.cursor/skills/msc-research-index/SKILL.md`",
        "Cursor rule: `.cursor/rules/msc-research-index.mdc`",
        "",
        "Query a cluster without listing the folder:",
        "",
        "```text",
        'python tools/msc_research_catalog.py --match "bird form func_143"',
        "```",
        "",
        "CodeGraph indexes the Python catalog (cluster ids and aliases), not the Markdown notes.",
        "Existing research notes are not rewritten by this index.",
        "",
        "## Clusters",
        "",
    ]
    for cluster in CLUSTERS:
        lines.append(f"### `{cluster.id}` — {cluster.title}")
        lines.append("")
        lines.append(f"- **kind:** {cluster.kind}")
        lines.append(f"- **aliases:** {', '.join(f'`{alias}`' for alias in cluster.aliases)}")
        if cluster.notes:
            lines.append(f"- **notes:** {cluster.notes}")
        if cluster.settled:
            lines.append("- **settled:**")
            lines.extend(f"  - {item}" for item in cluster.settled)
        if cluster.read_first:
            lines.append("- **read_first:**")
            lines.extend(f"  - `{path}`" for path in cluster.read_first)
        if cluster.docs:
            lines.append("- **docs:**")
            lines.extend(f"  - `{path}`" for path in cluster.docs)
        if cluster.related:
            lines.append("- **related:**")
            lines.extend(f"  - `{path}`" for path in cluster.related)
        if cluster.do_not:
            lines.append("- **do_not:**")
            lines.extend(f"  - {item}" for item in cluster.do_not)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def check_catalog() -> list[str]:
    errors: list[str] = []
    seen_ids: set[str] = set()
    for cluster in CLUSTERS:
        if cluster.id in seen_ids:
            errors.append(f"duplicate cluster id: {cluster.id}")
        seen_ids.add(cluster.id)
        if not cluster.read_first:
            errors.append(f"{cluster.id}: read_first is empty")
        for path in cluster.read_first + cluster.docs + cluster.related:
            disk = REPO_ROOT / path
            if not disk.exists():
                errors.append(f"{cluster.id}: missing path {path}")

    owned: set[str] = set()
    for cluster in CLUSTERS:
        owned |= owned_msc_research_paths(cluster)
    on_disk = on_disk_msc_research_paths()
    for path in sorted(on_disk - owned):
        errors.append(f"uncatalogued msc-research file: {path}")
    for path in sorted(owned - on_disk):
        errors.append(f"catalog path not on disk: {path}")

    if INDEX_PATH.exists():
        actual = INDEX_PATH.read_text(encoding="utf-8")
        expected = render_index()
        if actual != expected:
            errors.append(
                "docs/msc-research/INDEX.md is stale; run "
                "python tools/msc_research_catalog.py --write-index"
            )
    else:
        errors.append("docs/msc-research/INDEX.md is missing; run --write-index")
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = ArgumentParser(description="Route MSC research notes by cluster.")
    parser.add_argument("--list", action="store_true", help="List cluster ids")
    parser.add_argument("--match", metavar="QUERY", help="Rank clusters for a task query")
    parser.add_argument("--print", dest="print_id", metavar="CLUSTER", help="Print one cluster")
    parser.add_argument("--check", action="store_true", help="Validate catalog coverage")
    parser.add_argument("--write-index", action="store_true", help="Write docs/msc-research/INDEX.md")
    parser.add_argument("--limit", type=int, default=5, help="Max --match hits")
    args = parser.parse_args(argv)

    selected = [
        bool(args.list),
        bool(args.match),
        bool(args.print_id),
        bool(args.check),
        bool(args.write_index),
    ]
    if sum(selected) != 1:
        parser.error("choose exactly one of --list / --match / --print / --check / --write-index")

    if args.list:
        for cluster in CLUSTERS:
            print(f"{cluster.id}\t{cluster.kind}\t{cluster.title}")
        return 0

    if args.print_id:
        cluster = CLUSTER_BY_ID.get(args.print_id)
        if cluster is None:
            print(f"unknown cluster: {args.print_id}", file=sys.stderr)
            print("known:", ", ".join(CLUSTER_BY_ID), file=sys.stderr)
            return 1
        print(format_cluster(cluster))
        return 0

    if args.match:
        ranked = match_clusters(args.match, limit=args.limit)
        if not ranked:
            print("no cluster matched")
            print("known:")
            for cluster in CLUSTERS:
                print(f"- {cluster.id}: {cluster.title}")
            return 1
        print("matches:")
        for score, cluster in ranked:
            print(f"- {cluster.id} ({score}) {cluster.title}")
        print("---")
        print(format_cluster(ranked[0][1]))
        if len(ranked) > 1 and ranked[1][0] >= max(12, ranked[0][0] // 3):
            print("---")
            print(format_cluster(ranked[1][1]))
        return 0

    if args.write_index:
        INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        INDEX_PATH.write_text(render_index(), encoding="utf-8", newline="\n")
        print(f"wrote {INDEX_PATH.relative_to(REPO_ROOT).as_posix()}")
        return 0

    errors = check_catalog()
    if errors:
        for error in errors:
            print(error)
        return 1
    print(
        f"OK: {len(CLUSTERS)} clusters, "
        f"{len(on_disk_msc_research_paths())} msc-research files catalogued"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
